import type { PlaybookId } from "@trader-os/shared";
import type { Candle } from "./market-data.js";
import { getWarehouseBars, syncDailyHistoryFree } from "./market-warehouse.js";

export interface BacktestTrade {symbol:string;playbook:PlaybookId;signalAt:string;entryAt:string;entry:number;stop:number;target:number;exitAt:string;exit:number;r:number;outcome:"WIN"|"LOSS"|"TIME"}
export interface BacktestMetrics {samples:number;wins:number;losses:number;winRatePct:number;avgR:number;expectancyR:number;maxLossStreak:number}
export interface WalkForwardResult {symbol:string;playbook:PlaybookId;generatedAt:string;bars:number;train:BacktestMetrics;test:BacktestMetrics;all:BacktestMetrics;robustness:"STRONG"|"PROMISING"|"WEAK"|"INSUFFICIENT";warning?:string;trades:BacktestTrade[]}

function mean(a:number[]){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}
function sma(a:number[],p:number,i:number){if(i+1<p)return undefined;return mean(a.slice(i+1-p,i+1))}
function atr(b:Candle[],p:number,i:number){if(i<p)return undefined;const tr:number[]=[];for(let j=i-p+1;j<=i;j++){const prev=b[j-1];const c=b[j];if(!prev)continue;tr.push(Math.max(c.high-c.low,Math.abs(c.high-prev.close),Math.abs(c.low-prev.close)))}return tr.length?mean(tr):undefined}
function avgVol(b:Candle[],p:number,i:number){if(i+1<p)return undefined;return mean(b.slice(i+1-p,i+1).map(x=>x.volume))}
function high(b:Candle[],from:number,to:number){return Math.max(...b.slice(from,to+1).map(x=>x.high))}
function low(b:Candle[],from:number,to:number){return Math.min(...b.slice(from,to+1).map(x=>x.low))}
function metric(trades:BacktestTrade[]):BacktestMetrics{const wins=trades.filter(x=>x.r>0).length,losses=trades.filter(x=>x.r<0).length;let streak=0,max=0;for(const t of trades){if(t.r<0){streak++;max=Math.max(max,streak)}else streak=0}const avgR=trades.length?mean(trades.map(x=>x.r)):0;return{samples:trades.length,wins,losses,winRatePct:trades.length?Number((wins/trades.length*100).toFixed(1)):0,avgR:Number(avgR.toFixed(2)),expectancyR:Number(avgR.toFixed(2)),maxLossStreak:max}}

function signal(playbook:PlaybookId,b:Candle[],i:number){const closes=b.map(x=>x.close),s20=sma(closes,20,i),s50=sma(closes,50,i),a=atr(b,14,i),v=avgVol(b,20,i);if(!s20||!s50||!a||!v||i<55)return undefined;const c=b[i],prev20High=high(b,i-20,i-1),recent5Low=low(b,i-5,i),trend=s20>s50&&c.close>s50;
  if(playbook==="BREAKOUT"||playbook==="RELATIVE_STRENGTH_BREAKOUT"){if(!(trend&&c.close>prev20High&&c.volume>=v*1.15))return undefined;const entry=b[i+1]?.open;if(!entry)return undefined;const stop=Math.min(recent5Low,entry-a*.9),risk=entry-stop;if(risk<=0||risk>a*2.2)return undefined;return{entry,stop,target:entry+risk*2.2}}
  if(playbook==="PULLBACK"||playbook==="SUPPORT_BOUNCE"){if(!(trend&&Math.abs(c.close-s20)<=a*.7&&c.close>=s50&&c.volume<=v*1.25))return undefined;const n=b[i+1];if(!n||n.open<c.low)return undefined;const entry=n.open,stop=Math.min(recent5Low,s20-a*.35),risk=entry-stop;if(risk<=0||risk>a*2)return undefined;return{entry,stop,target:entry+risk*2}}
  if(playbook==="TREND_RECLAIM"){const prev=b[i-1];if(!(trend&&prev.close<s20&&c.close>s20&&c.volume>=v))return undefined;const entry=b[i+1]?.open;if(!entry)return undefined;const stop=Math.min(c.low,s20-a*.45),risk=entry-stop;if(risk<=0)return undefined;return{entry,stop,target:entry+risk*2}}
  if(playbook==="VOLATILITY_SQUEEZE"){const ranges=b.slice(i-10,i).map(x=>x.high-x.low),avgRange=mean(ranges),todayRange=c.high-c.low;if(!(trend&&todayRange<avgRange*.7&&c.close>c.open))return undefined;const entry=Math.max(c.high,b[i+1]?.open??0);if(!entry)return undefined;const stop=Math.min(recent5Low,entry-a),risk=entry-stop;if(risk<=0)return undefined;return{entry,stop,target:entry+risk*2.3}}
  return undefined;
}

export function runDailyBacktest(symbol:string,bars:Candle[],playbook:PlaybookId):BacktestTrade[]{const out:BacktestTrade[]=[];for(let i=60;i<bars.length-4;i++){const s=signal(playbook,bars,i);if(!s)continue;let exit=s.entry,outcome:BacktestTrade["outcome"]="TIME",exitIdx=Math.min(i+3,bars.length-1);for(let j=i+1;j<=Math.min(i+3,bars.length-1);j++){const x=bars[j];if(x.low<=s.stop&&x.high>=s.target){exit=s.stop;outcome="LOSS";exitIdx=j;break}if(x.low<=s.stop){exit=s.stop;outcome="LOSS";exitIdx=j;break}if(x.high>=s.target){exit=s.target;outcome="WIN";exitIdx=j;break}exit=x.close;exitIdx=j}const risk=s.entry-s.stop,r=risk>0?(exit-s.entry)/risk:0;out.push({symbol,playbook,signalAt:new Date(bars[i].time*1000).toISOString(),entryAt:new Date(bars[i+1].time*1000).toISOString(),entry:Number(s.entry.toFixed(4)),stop:Number(s.stop.toFixed(4)),target:Number(s.target.toFixed(4)),exitAt:new Date(bars[exitIdx].time*1000).toISOString(),exit:Number(exit.toFixed(4)),r:Number(r.toFixed(2)),outcome});i=Math.max(i,exitIdx)}return out}

export async function walkForwardBacktest(symbol:string,playbook:PlaybookId,options:{sync?:boolean;years?:number}={}):Promise<WalkForwardResult>{const sym=symbol.trim().toUpperCase();if(options.sync!==false)try{await syncDailyHistoryFree(sym,options.years??5,false)}catch{}const bars=getWarehouseBars(sym,"1d",5000),trades=runDailyBacktest(sym,bars,playbook);const split=Math.max(1,Math.floor(trades.length*.7)),trainTrades=trades.slice(0,split),testTrades=trades.slice(split),train=metric(trainTrades),test=metric(testTrades),all=metric(trades);let robustness:WalkForwardResult["robustness"]="INSUFFICIENT";if(trades.length>=20&&test.samples>=5){if(train.avgR>0.15&&test.avgR>0.1&&test.winRatePct>=45)robustness="STRONG";else if(train.avgR>0&&test.avgR>0)robustness="PROMISING";else robustness="WEAK"}return{symbol:sym,playbook,generatedAt:new Date().toISOString(),bars:bars.length,train,test,all,robustness,warning:bars.length<150?"אין עדיין מספיק היסטוריה מקומית. אפשר לחבר Alpaca Basic חינמי כדי לסנכרן היסטוריה מ-2016.":undefined,trades:trades.slice(-100)}}
