import type { TradePlan } from "@trader-os/shared";
import { alpacaFreeStatus, getAlpacaSnapshots } from "./alpaca-free.js";
import { getSecCompanyIntelligence, type SecCompanyIntelligence } from "./sec-intelligence.js";

export interface DataConfidenceReport {symbol:string;score:number;grade:"HIGH"|"MEDIUM"|"LOW"|"BLOCK";asOf:string;checks:Array<{key:string;label:string;ok:boolean;weight:number;details:string;source?:string}>;crossProvider?:{primaryPrice?:number;secondaryPrice?:number;differencePct?:number;status:"OK"|"WARN"|"BLOCK"|"UNAVAILABLE"};liquidity?:{bid?:number;ask?:number;spreadPct?:number;source?:string;status:"GOOD"|"WARN"|"BAD"|"UNKNOWN"};sec?:SecCompanyIntelligence}

function ageSeconds(ts?:string){const x=ts?Date.parse(ts):NaN;return Number.isFinite(x)?Math.max(0,(Date.now()-x)/1000):999999}
export async function buildDataConfidence(plan:TradePlan,opts:{includeSec?:boolean;includeAlpaca?:boolean}={}):Promise<DataConfidenceReport>{const sym=plan.symbol.toUpperCase(),checks:DataConfidenceReport["checks"]=[],add=(key:string,label:string,ok:boolean,weight:number,details:string,source?:string)=>checks.push({key,label,ok,weight,details,source});const q=plan.quote,age=ageSeconds(q?.timestamp);add("quote","מחיר שוק תקין",Boolean(q?.price&&q.price>0),20,q?.price?`$${q.price.toFixed(2)} · גיל ${Math.round(age)} שנ׳`:`לא התקבל מחיר תקין`,q?.source);add("fresh","טריות מחיר",age<=45,15,age<=45?"המחיר טרי מספיק למעקב":`המחיר בן ${Math.round(age)} שניות`,q?.source);add("ohlcv","היסטוריית OHLCV",(plan.dataQualityPct??0)>=75,20,`איכות בסיסית ${plan.dataQualityPct??0}%`,plan.dataSource);add("mtf","Multi-Timeframe",(plan.technicals?.mtfQualityPct??0)>=70,15,`איכות MTF ${plan.technicals?.mtfQualityPct??0}%`,plan.dataSource);add("liquidity","מחזור דולרי",(plan.technicals?.averageDollarVolume20d??0)>=Number(process.env.MIN_AVG_DOLLAR_VOLUME_20D??5000000),10,plan.technicals?.averageDollarVolume20d?`$${Math.round(plan.technicals.averageDollarVolume20d).toLocaleString("en-US")} ממוצע 20 יום`:`לא זמין`,plan.dataSource);
  let cross:DataConfidenceReport["crossProvider"]={status:"UNAVAILABLE"},liquidity:DataConfidenceReport["liquidity"]={status:"UNKNOWN"},sec:SecCompanyIntelligence|undefined;
  if(opts.includeAlpaca!==false&&alpacaFreeStatus().configured){try{const snap=(await getAlpacaSnapshots([sym]))[sym];if(snap){const secondary=snap.quote?.price,primary=q?.price,diff=secondary&&primary?Math.abs(secondary-primary)/((secondary+primary)/2)*100:undefined;cross={primaryPrice:primary,secondaryPrice:secondary,differencePct:diff,status:diff===undefined?"UNAVAILABLE":diff<=1?"OK":diff<=3?"WARN":"BLOCK"};add("cross_provider","אימות מחיר מול ספק שני",cross.status!=="BLOCK",10,diff===undefined?"אין מחיר להשוואה":`פער ${diff.toFixed(2)}% בין ${q?.source??"ספק ראשי"} ל-Alpaca IEX`,"Alpaca IEX");const sp=snap.spreadPct;liquidity={bid:snap.bid,ask:snap.ask,spreadPct:sp,source:"Alpaca IEX quote (proxy, לא NBBO מלא)",status:sp===undefined?"UNKNOWN":sp<=.35?"GOOD":sp<=.8?"WARN":"BAD"};add("spread","ספרד ביצוע",liquidity.status!=="BAD",5,sp===undefined?"Bid/Ask לא זמין":`ספרד IEX משוער ${sp.toFixed(2)}%`,"Alpaca IEX")}}catch(e){add("alpaca","ספק אימות משני",false,5,e instanceof Error?e.message:String(e),"Alpaca IEX")}}
  if(opts.includeSec!==false){try{sec=await getSecCompanyIntelligence(sym,false);add("identity","זהות חברה/בורסה מאומתת",Boolean(sec.identity.cik&&sec.identity.exchange),5,sec.identity.exchange?`${sec.identity.name??sym} · ${sec.identity.exchange}`:"לא נמצא CIK/Exchange מאומת","SEC EDGAR");add("sec_risk","אין סיכון SEC קריטי טרי",!sec.criticalFilingRisk,10,sec.criticalFilingRisk?(sec.filingRiskReason??"נמצא filing קריטי"):"לא זוהה filing קריטי בטווח האחרון","SEC EDGAR")}catch(e){add("sec","SEC Intelligence",false,5,e instanceof Error?e.message:String(e),"SEC EDGAR")}}
  const total=checks.reduce((s,x)=>s+x.weight,0),earned=checks.reduce((s,x)=>s+(x.ok?x.weight:0),0);let score=total?Math.round(earned/total*100):0;if(cross.status==="BLOCK")score=Math.min(score,55);if(sec?.criticalFilingRisk)score=Math.min(score,50);const grade:DataConfidenceReport["grade"]=score>=85?"HIGH":score>=70?"MEDIUM":score>=55?"LOW":"BLOCK";return{symbol:sym,score,grade,asOf:new Date().toISOString(),checks,crossProvider:cross,liquidity,sec}}
