import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { dataPath, isoNow, readJsonFile, writeJsonFile } from "./store.js";

export interface ShortContext {
  symbol:string;
  asOf:string;
  shortInterest?:{settlementDate?:string;shortShares?:number;previousShortShares?:number;daysToCover?:number;changePct?:number;source:string};
  shortVolume?:{tradeDate?:string;shortVolume?:number;totalVolume?:number;shortVolumePct?:number;source:string;note:string};
  failsToDeliver?:{settlementDate?:string;quantity?:number;price?:number;source:string;note:string};
  regShoThreshold?:{listed:boolean;source:string;asOf:string};
  squeezeScore:number;
  confidence:"LOW"|"MEDIUM"|"HIGH";
  warnings:string[];
}
export interface HaltRecord {symbol:string;halted:boolean;haltTime?:string;resumeTime?:string;reason?:string;source:string;asOf:string}

const finraBase=(process.env.FINRA_API_BASE_URL??"https://api.finra.org").replace(/\/$/,"");
const finraTtl=Math.max(5*60_000,Number(process.env.FINRA_CACHE_MS??30*60_000));
const haltTtl=Math.max(60_000,Number(process.env.NASDAQ_HALT_CACHE_MS??60_000));
const ftdTtl=Math.max(6*60*60_000,Number(process.env.SEC_FTD_CACHE_MS??24*60*60_000));
const timeoutMs=Math.max(3000,Number(process.env.FREE_CONTEXT_TIMEOUT_MS??10000));

function fresh(ts?:string,ttl=finraTtl){return Boolean(ts&&Date.now()-Date.parse(ts)<ttl)}
async function fetchText(url:string,opts:RequestInit={}):Promise<string>{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetch(url,{...opts,signal:ctl.signal,headers:{"user-agent":process.env.SEC_USER_AGENT??"TraderOS/3 personal-use",accept:"*/*",...(opts.headers??{})}});const text=await r.text();if(!r.ok)throw new Error(`${r.status}: ${text.slice(0,180)}`);return text}finally{clearTimeout(t)}}
async function finraPost(dataset:string,payload:any){const text=await fetchText(`${finraBase}/data/group/otcMarket/name/${dataset}`,{method:"POST",headers:{"content-type":"application/json",accept:"application/json"},body:JSON.stringify(payload)});return JSON.parse(text) as any[]}
function n(x:any){const v=Number(x);return Number.isFinite(v)?v:undefined}

async function shortInterest(symbol:string){const rows=await finraPost("consolidatedShortInterest",{limit:50,compareFilters:[{compareType:"equal",fieldName:"symbolCode",fieldValue:symbol}]});const row=[...rows].sort((a,b)=>Date.parse(String(b.settlementDate??""))-Date.parse(String(a.settlementDate??"")))[0];if(!row)return undefined;return{settlementDate:String(row.settlementDate??""),shortShares:n(row.currentShortPositionQuantity),previousShortShares:n(row.previousShortPositionQuantity),daysToCover:n(row.daysToCoverQuantity),changePct:n(row.changePercent),source:"FINRA Consolidated Short Interest"}}
async function shortVolume(symbol:string){const rows=await finraPost("regShoDaily",{limit:80,fields:["tradeReportDate","securitiesInformationProcessorSymbolIdentifier","shortParQuantity","shortExemptParQuantity","totalParQuantity"],compareFilters:[{compareType:"equal",fieldName:"securitiesInformationProcessorSymbolIdentifier",fieldValue:symbol}]});const byDate=new Map<string,{short:number;total:number}>();for(const r of rows){const d=String(r.tradeReportDate??"");if(!d)continue;const x=byDate.get(d)??{short:0,total:0};x.short+=n(r.shortParQuantity)??0;x.total+=n(r.totalParQuantity)??0;byDate.set(d,x)}const latest=[...byDate.entries()].sort((a,b)=>Date.parse(b[0])-Date.parse(a[0]))[0];if(!latest)return undefined;return{tradeDate:latest[0],shortVolume:latest[1].short,totalVolume:latest[1].total,shortVolumePct:latest[1].total?Number((latest[1].short/latest[1].total*100).toFixed(1)):undefined,source:"FINRA Reg SHO Daily Short Sale Volume",note:"זהו short-sale volume מדווח מחוץ לבורסות, לא Short Interest ולא מדד ישיר לפוזיציות שורט פתוחות."}}

async function thresholdStatus(symbol:string){const path=dataPath("nasdaq-threshold-cache.json"),old=readJsonFile<any>(path,{});let html=old.html as string|undefined,at=old.at as string|undefined;if(!html||!fresh(at,6*60*60_000)){html=await fetchText("https://www.nasdaqtrader.com/trader.aspx?id=RegSHOThreshold");at=isoNow();writeJsonFile(path,{at,html})}const plain=html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ");return{listed:new RegExp(`(?:^|\\s)${symbol.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(?:\\s|$)`,`i`).test(plain),source:"Nasdaq Trader Reg SHO Threshold List",asOf:at??isoNow()}}

function parseFtd(text:string){const lines=text.split(/\r?\n/),map:Record<string,{settlementDate:string;quantity:number;price?:number}>={};for(const line of lines){const p=line.split("|");if(p.length<5||!/^[0-9]{8}$/.test(p[0]??""))continue;const symbol=String(p[2]??"").trim().toUpperCase(),qty=n(p[3]);if(!symbol||qty===undefined)continue;const date=`${p[0].slice(0,4)}-${p[0].slice(4,6)}-${p[0].slice(6,8)}`,prev=map[symbol];if(!prev||Date.parse(date)>=Date.parse(prev.settlementDate))map[symbol]={settlementDate:date,quantity:qty,price:n(p[5])}}return map}
async function latestFtdMap(){const path=dataPath("sec-ftd-latest.json"),old=readJsonFile<any>(path,{map:{}});if(fresh(old.at,ftdTtl)&&Object.keys(old.map??{}).length)return old.map as Record<string,any>;const page=await fetchText("https://www.sec.gov/data-research/sec-markets-data/fails-deliver-data");const href=[...page.matchAll(/href=["']([^"']+\.zip)["']/gi)].map(m=>m[1]).find(Boolean);if(!href)throw new Error("SEC FTD ZIP link not found");const url=new URL(href,"https://www.sec.gov").toString(),dir=mkdtempSync(join(tmpdir(),"trader-os-ftd-")),zip=join(dir,"ftd.zip");try{const buf=await (async()=>{const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),timeoutMs*3);try{const r=await fetch(url,{signal:ctl.signal,headers:{"user-agent":process.env.SEC_USER_AGENT??"TraderOS/3 personal-use"}});if(!r.ok)throw new Error(`SEC FTD ${r.status}`);return Buffer.from(await r.arrayBuffer())}finally{clearTimeout(t)}})();writeFileSync(zip,buf);const proc=spawnSync("unzip",["-p",zip],{encoding:"utf8",maxBuffer:32*1024*1024});if(proc.status!==0)throw new Error(`unzip failed: ${proc.stderr?.slice(0,160)}`);const map=parseFtd(proc.stdout);writeJsonFile(path,{at:isoNow(),sourceUrl:url,map});return map}finally{rmSync(dir,{recursive:true,force:true})}}
async function ftdFor(symbol:string){const map=await latestFtdMap(),x=map[symbol];return x?{...x,source:"SEC Fails-to-Deliver",note:"FTD הוא מלאי מצטבר של fails בנקודת זמן ואינו הוכחה לשורט או naked shorting."}:undefined}

export async function getShortContext(symbol:string,force=false):Promise<ShortContext>{const sym=symbol.trim().toUpperCase(),path=dataPath(`market-context/${sym}-short.json`),old=readJsonFile<ShortContext|null>(path,null);if(!force&&old&&fresh(old.asOf))return old;const warnings:string[]=[];const [si,sv,th,ftd]=await Promise.all([shortInterest(sym).catch(e=>(warnings.push(`Short Interest: ${e instanceof Error?e.message:String(e)}`),undefined)),shortVolume(sym).catch(e=>(warnings.push(`Short Volume: ${e instanceof Error?e.message:String(e)}`),undefined)),thresholdStatus(sym).catch(e=>(warnings.push(`Reg SHO: ${e instanceof Error?e.message:String(e)}`),undefined)),ftdFor(sym).catch(e=>(warnings.push(`FTD: ${e instanceof Error?e.message:String(e)}`),undefined))]);let score=0;if((si?.daysToCover??0)>=4)score+=24;if((si?.changePct??0)>=10)score+=15;if((sv?.shortVolumePct??0)>=55)score+=14;if(th?.listed)score+=24;if(ftd?.quantity&&si?.shortShares&&ftd.quantity/si.shortShares>.01)score+=12;score=Math.min(100,score);const confidence=si&&sv&&th?"HIGH":(si||sv)&&th?"MEDIUM":"LOW";const out:ShortContext={symbol:sym,asOf:isoNow(),shortInterest:si,shortVolume:sv,failsToDeliver:ftd,regShoThreshold:th,squeezeScore:score,confidence,warnings};writeJsonFile(path,out);return out}

function xmlVal(item:string,tag:string){const m=item.match(new RegExp(`<${tag}(?:\\s[^>]*)?>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?<\\/${tag}>`,`i`));return m?.[1]?.replace(/<[^>]+>/g," ").trim()}
export async function getCurrentHalts(force=false){const path=dataPath("nasdaq-halts.json"),old=readJsonFile<{at?:string;rows:HaltRecord[]}>(path,{rows:[]});if(!force&&fresh(old.at,haltTtl))return old.rows;const xml=await fetchText("https://www.nasdaqtrader.com/rss.aspx?feed=tradehalts");const items=[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].map(m=>m[1]),rows:HaltRecord[]=[];for(const item of items){const symbol=(xmlVal(item,"ndaq:IssueSymbol")||xmlVal(item,"title")||"").split(/\s|-/)[0].toUpperCase();if(!symbol||symbol.length>12)continue;rows.push({symbol,halted:true,haltTime:xmlVal(item,"ndaq:HaltTime")||undefined,resumeTime:xmlVal(item,"ndaq:ResumptionTradeTime")||undefined,reason:xmlVal(item,"ndaq:ReasonCode")||xmlVal(item,"description")||undefined,source:"Nasdaq Trader Halt RSS",asOf:isoNow()})}writeJsonFile(path,{at:isoNow(),rows});return rows}
export async function getHaltForSymbol(symbol:string,force=false){const sym=symbol.trim().toUpperCase();return (await getCurrentHalts(force)).find(x=>x.symbol===sym)??{symbol:sym,halted:false,source:"Nasdaq Trader Halt RSS",asOf:isoNow()}}
export function externalMarketContextStatus(){return{finra:{enabled:true,source:"FINRA Query API",cacheMinutes:finraTtl/60000},secFtd:{enabled:true,source:"SEC FTD",requiresUnzip:true,cacheHours:ftdTtl/3600000},nasdaq:{halts:true,threshold:true,haltRefreshSeconds:haltTtl/1000},costUsd:0}}
