import { createRequire } from "node:module";
import { resolve } from "node:path";
import type { Candle } from "./market-data.js";
import { dataDir } from "./store.js";
import { alpacaFreeStatus, getAlpacaBars } from "./alpaca-free.js";

let db:any=null,dbError:string|undefined;
function getDb(){if(db)return db;if(dbError)return null;try{const require=createRequire(import.meta.url),{DatabaseSync}=require("node:sqlite") as any;db=new DatabaseSync(resolve(dataDir,"trader-os.db"));db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;
CREATE TABLE IF NOT EXISTS market_bars(symbol TEXT NOT NULL,timeframe TEXT NOT NULL,t INTEGER NOT NULL,o REAL NOT NULL,h REAL NOT NULL,l REAL NOT NULL,c REAL NOT NULL,v REAL NOT NULL,source TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(symbol,timeframe,t));
CREATE INDEX IF NOT EXISTS idx_market_bars_symbol_tf_t ON market_bars(symbol,timeframe,t);
CREATE TABLE IF NOT EXISTS warehouse_sync(symbol TEXT NOT NULL,timeframe TEXT NOT NULL,last_sync TEXT NOT NULL,source TEXT NOT NULL,bars INTEGER NOT NULL,PRIMARY KEY(symbol,timeframe));`);return db}catch(e){dbError=e instanceof Error?e.message:String(e);return null}}

export function upsertWarehouseBars(symbol:string,timeframe:string,bars:Candle[],source:string){const d=getDb();if(!d||!bars.length)return{stored:0,backend:"unavailable",error:dbError};const sym=symbol.trim().toUpperCase(),now=new Date().toISOString(),stmt=d.prepare(`INSERT INTO market_bars(symbol,timeframe,t,o,h,l,c,v,source,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(symbol,timeframe,t) DO UPDATE SET o=excluded.o,h=excluded.h,l=excluded.l,c=excluded.c,v=excluded.v,source=excluded.source,updated_at=excluded.updated_at`);d.exec("BEGIN IMMEDIATE");try{for(const b of bars)stmt.run(sym,timeframe,b.time,b.open,b.high,b.low,b.close,b.volume,source,now);d.prepare(`INSERT INTO warehouse_sync(symbol,timeframe,last_sync,source,bars) VALUES(?,?,?,?,?) ON CONFLICT(symbol,timeframe) DO UPDATE SET last_sync=excluded.last_sync,source=excluded.source,bars=excluded.bars`).run(sym,timeframe,now,source,bars.length);d.exec("COMMIT")}catch(e){try{d.exec("ROLLBACK")}catch{}throw e}return{stored:bars.length,backend:"sqlite",source}}
export function getWarehouseBars(symbol:string,timeframe:string,limit=1000):Candle[]{const d=getDb();if(!d)return[];const rows=d.prepare(`SELECT t,o,h,l,c,v FROM market_bars WHERE symbol=? AND timeframe=? ORDER BY t DESC LIMIT ?`).all(symbol.trim().toUpperCase(),timeframe,Math.max(1,Math.min(10000,limit))) as any[];return rows.reverse().map(r=>({time:Number(r.t),open:Number(r.o),high:Number(r.h),low:Number(r.l),close:Number(r.c),volume:Number(r.v)}))}
export function getWarehouseSymbols(){const d=getDb();if(!d)return[];return (d.prepare(`SELECT symbol, timeframe, COUNT(*) bars, MIN(t) first_t, MAX(t) last_t, MAX(updated_at) updated_at FROM market_bars GROUP BY symbol,timeframe ORDER BY symbol,timeframe`).all() as any[]).map(r=>({...r,bars:Number(r.bars),first:new Date(Number(r.first_t)*1000).toISOString(),last:new Date(Number(r.last_t)*1000).toISOString()}))}
export function warehouseStatus(){const d=getDb();if(!d)return{available:false,error:dbError};const row=d.prepare(`SELECT COUNT(*) rows, COUNT(DISTINCT symbol) symbols FROM market_bars`).get() as any;const sync=d.prepare(`SELECT MAX(last_sync) last_sync FROM warehouse_sync`).get() as any;return{available:true,rows:Number(row?.rows??0),symbols:Number(row?.symbols??0),lastSync:sync?.last_sync,alpaca:alpacaFreeStatus()}}

export async function syncDailyHistoryFree(symbol:string,years=4,force=false){const status=alpacaFreeStatus();if(!status.configured)throw new Error("ALPACA_API_KEY_ID/ALPACA_API_SECRET_KEY חסרים — סנכרון היסטוריה חינמי מ-Alpaca אינו פעיל");const sym=symbol.trim().toUpperCase(),existing=getWarehouseBars(sym,"1d",30);if(!force&&existing.length&&Date.now()-existing.at(-1)!.time*1000<24*60*60_000)return{symbol:sym,reused:true,bars:getWarehouseBars(sym,"1d",5000).length};const end=new Date(Date.now()-16*60_000).toISOString(),start=new Date(Date.now()-Math.max(1,Math.min(9,years))*365.25*86400_000).toISOString();const bars=await getAlpacaBars(sym,"1Day",start,end,5000);upsertWarehouseBars(sym,"1d",bars,"Alpaca IEX historical");return{symbol:sym,reused:false,bars:bars.length,source:"Alpaca IEX historical",start,end}}

export function recordDeepAnalysisBars(symbol:string,intraday:Candle[],daily:Candle[],source:string){const a=upsertWarehouseBars(symbol,"5m",intraday,source),b=upsertWarehouseBars(symbol,"1d",daily,source);return{intraday:a,daily:b}}
