import { dataPath, readJsonFile, writeJsonFile } from "./store.js";

export type NewsTone="POSITIVE"|"NEGATIVE"|"NEUTRAL"|"MIXED"|"UNKNOWN";
export interface NewsItem{headline:string;summary?:string;url?:string;source?:string;datetime:string;category:string;tone:"POSITIVE"|"NEGATIVE"|"NEUTRAL";weight:number;critical:boolean}
export interface NewsSignal{symbol:string;available:boolean;asOf:string;tone:NewsTone;positiveScore:number;negativeScore:number;criticalNegative:boolean;items:NewsItem[];warning?:string}
const key=(process.env.FINNHUB_API_KEY??"").trim();const ttl=Math.max(60_000,Number(process.env.NEWS_CACHE_MS??10*60_000));
const pos:[RegExp,string,number][]=[[/\bupgrade|raised to|price target raised\b/i,"ANALYST_UPGRADE",2],[/\bcontract|award|selected|partnership|deal|agreement\b/i,"CONTRACT",2],[/\bacquisition|acquire|merger|buyout\b/i,"M&A",2],[/\bapproval|approved|clearance\b/i,"APPROVAL",2],[/\bbeat|beats|record revenue|raises guidance|raised guidance\b/i,"POSITIVE_RESULTS",2]];
const neg:[RegExp,string,number,boolean][]=[[/\boffering|public offering|registered direct|dilution|share sale\b/i,"OFFERING",4,true],[/\bbankruptcy|chapter 11|insolvency|going concern\b/i,"DISTRESS",5,true],[/\binvestigation|subpoena|fraud|sec probe\b/i,"INVESTIGATION",4,true],[/\bdowngrade|cut to|price target cut\b/i,"ANALYST_DOWNGRADE",2,false],[/\blawsuit|litigation|sued|recall\b/i,"LEGAL_RECALL",3,false],[/\bmisses|missed estimates|cuts guidance|lowered guidance|warning\b/i,"NEGATIVE_RESULTS",3,false]];
function classify(text:string){for(const[r,c,w,critical]of neg)if(r.test(text))return{tone:"NEGATIVE" as const,category:c,weight:w,critical};for(const[r,c,w]of pos)if(r.test(text))return{tone:"POSITIVE" as const,category:c,weight:w,critical:false};return{tone:"NEUTRAL" as const,category:"GENERAL",weight:0,critical:false}}
function cachePath(symbol:string){return dataPath(`news-${symbol.toUpperCase()}.json`)}
function cached(symbol:string){return readJsonFile<NewsSignal|null>(cachePath(symbol),null)}
function dateStr(daysAgo:number){const d=new Date(Date.now()-daysAgo*86400000);return d.toISOString().slice(0,10)}
export async function getNewsSignal(symbol:string,force=false):Promise<NewsSignal>{const sym=symbol.trim().toUpperCase(),old=cached(sym);if(!force&&old&&Date.now()-Date.parse(old.asOf)<ttl)return old;if(!key)return{symbol:sym,available:false,asOf:new Date().toISOString(),tone:"UNKNOWN",positiveScore:0,negativeScore:0,criticalNegative:false,items:[],warning:"FINNHUB_API_KEY missing"};const q=new URLSearchParams({symbol:sym,from:dateStr(3),to:dateStr(0),token:key});const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),8000);try{const r=await fetch(`https://finnhub.io/api/v1/company-news?${q}`,{signal:ctl.signal,headers:{accept:"application/json"}});const text=await r.text();if(!r.ok)throw new Error(`Finnhub news ${r.status}: ${text.slice(0,180)}`);const raw=JSON.parse(text) as Array<{headline?:string;summary?:string;url?:string;source?:string;datetime?:number}>;const items=(Array.isArray(raw)?raw:[]).slice(0,20).flatMap(x=>{if(!x.headline)return[];const c=classify(`${x.headline} ${x.summary??""}`);return[{headline:x.headline,summary:x.summary,url:x.url,source:x.source,datetime:new Date((x.datetime??Date.now()/1000)*1000).toISOString(),...c}]});const positiveScore=items.filter(x=>x.tone==="POSITIVE").reduce((s,x)=>s+x.weight,0),negativeScore=items.filter(x=>x.tone==="NEGATIVE").reduce((s,x)=>s+x.weight,0),criticalNegative=items.some(x=>x.critical&&Date.now()-Date.parse(x.datetime)<36*60*60_000),tone:NewsTone=positiveScore>negativeScore+1?"POSITIVE":negativeScore>positiveScore+1?"NEGATIVE":positiveScore||negativeScore?"MIXED":"NEUTRAL",result:NewsSignal={symbol:sym,available:true,asOf:new Date().toISOString(),tone,positiveScore,negativeScore,criticalNegative,items};writeJsonFile(cachePath(sym),result);return result}catch(error){return old??{symbol:sym,available:false,asOf:new Date().toISOString(),tone:"UNKNOWN",positiveScore:0,negativeScore:0,criticalNegative:false,items:[],warning:error instanceof Error?error.message:String(error)}}finally{clearTimeout(timer)}}
