import { getActiveTrades, portfolioRiskSummary } from "./portfolio.js";
import { getCandles } from "./trader.js";
import { getSecurityIdentity } from "./sec-intelligence.js";
import { getWarehouseBars } from "./market-warehouse.js";

const factorMap:Record<string,string[]>={
  NVDA:["GROWTH_TECH","SEMIS","NASDAQ"],AMD:["GROWTH_TECH","SEMIS","NASDAQ"],AVGO:["GROWTH_TECH","SEMIS","NASDAQ"],MU:["SEMIS","NASDAQ"],ARM:["GROWTH_TECH","SEMIS","NASDAQ"],ANET:["GROWTH_TECH","TECH","NASDAQ"],SMCI:["GROWTH_TECH","TECH","NASDAQ"],PLTR:["GROWTH_TECH","TECH","NASDAQ"],CRWD:["CYBER","TECH","NASDAQ"],
  COIN:["CRYPTO_BETA","RISK_ON"],MARA:["CRYPTO_BETA","RISK_ON"],RIOT:["CRYPTO_BETA","RISK_ON"],HOOD:["FINTECH","RISK_ON"],SOFI:["FINTECH","RISK_ON"],
  BA:["INDUSTRIAL","CYCLICAL"],CAT:["INDUSTRIAL","CYCLICAL"],GE:["INDUSTRIAL","CYCLICAL"],RKLB:["SPACE","HIGH_BETA"],ASTS:["SPACE","HIGH_BETA"],
  TSLA:["HIGH_BETA","CONSUMER","NASDAQ"],RIVN:["HIGH_BETA","AUTO"],F:["AUTO","CYCLICAL"],GM:["AUTO","CYCLICAL"],
  CCL:["TRAVEL","CYCLICAL"],RCL:["TRAVEL","CYCLICAL"],UAL:["TRAVEL","CYCLICAL"],DAL:["TRAVEL","CYCLICAL"],
  AAPL:["MEGA_CAP","TECH","NASDAQ"],MSFT:["MEGA_CAP","TECH","NASDAQ"],META:["MEGA_CAP","COMMUNICATION","NASDAQ"],GOOGL:["MEGA_CAP","COMMUNICATION","NASDAQ"],AMZN:["MEGA_CAP","CONSUMER","NASDAQ"],
};
function factors(symbol:string){return factorMap[symbol.toUpperCase()]??["UNCLASSIFIED"]}
function sectorFactors(sector?:string,industry?:string){const s=String(sector??"").toUpperCase(),i=String(industry??"").toUpperCase(),out:string[]=[];if(/TECH|SOFTWARE|SEMICONDUCTOR|COMPUTER/.test(s+" "+i))out.push("TECH");if(/SEMICONDUCTOR/.test(i))out.push("SEMIS");if(/FINANCE|BANK|INSURANCE/.test(s+" "+i))out.push("FINANCIALS");if(/INDUSTR|AEROSPACE|MACHIN/.test(s+" "+i))out.push("INDUSTRIAL");if(/HEALTH|BIOTECH|PHARMA/.test(s+" "+i))out.push("HEALTHCARE");if(/ENERGY|OIL|GAS/.test(s+" "+i))out.push("ENERGY");if(/CONSUMER|RETAIL|AUTO/.test(s+" "+i))out.push("CONSUMER");if(/COMMUNICATION|MEDIA|TELECOM/.test(s+" "+i))out.push("COMMUNICATION");return out.length?[...new Set(out)]:["UNCLASSIFIED"]}
async function factorsDynamic(symbol:string){const fixed=factorMap[symbol.toUpperCase()];if(fixed)return fixed;try{const id:any=await getSecurityIdentity(symbol,false);return sectorFactors(id?.sector,id?.sicDescription??id?.industry)}catch{return["UNCLASSIFIED"]}}
function returns(values:number[]){const out:number[]=[];for(let i=1;i<values.length;i++)if(values[i-1])out.push(values[i]/values[i-1]-1);return out}
function pearson(a:number[],b:number[]){const n=Math.min(a.length,b.length);if(n<8)return undefined;const x=a.slice(-n),y=b.slice(-n),mx=x.reduce((s,v)=>s+v,0)/n,my=y.reduce((s,v)=>s+v,0)/n;let num=0,dx=0,dy=0;for(let i=0;i<n;i++){const ax=x[i]-mx,by=y[i]-my;num+=ax*by;dx+=ax*ax;dy+=by*by}const den=Math.sqrt(dx*dy);return den?Number((num/den).toFixed(3)):undefined}
let cache:{at:number;value:any}|null=null;

export async function getPortfolioIntelligence(force=false){if(!force&&cache&&Date.now()-cache.at<10*60_000)return cache.value;const trades=getActiveTrades().filter(x=>x.executionState==="RECORDED");const risk=portfolioRiskSummary();const factorExposure:Record<string,{trades:number;riskUsd:number;symbols:string[]}>= {};const factorRows=new Map<string,string[]>();await Promise.all(trades.map(async t=>factorRows.set(t.symbol,await factorsDynamic(t.symbol))));for(const t of trades){for(const f of factorRows.get(t.symbol)??["UNCLASSIFIED"]){const x=factorExposure[f]??{trades:0,riskUsd:0,symbols:[]};x.trades++;x.riskUsd+=t.riskUsd??0;if(!x.symbols.includes(t.symbol))x.symbols.push(t.symbol);factorExposure[f]=x}}
  const correlations:Array<{a:string;b:string;correlation?:number;warning:boolean}>=[];const closes=new Map<string,number[]>();await Promise.all(trades.slice(0,8).map(async t=>{try{const local=getWarehouseBars(t.symbol,"1d",120);if(local.length>=30){closes.set(t.symbol,local.slice(-80).map(x=>x.close));return}const c=await getCandles(t.symbol);closes.set(t.symbol,c.slice(-80).map(x=>x.close))}catch{}}));const symbols=[...closes.keys()];for(let i=0;i<symbols.length;i++)for(let j=i+1;j<symbols.length;j++){const c=pearson(returns(closes.get(symbols[i])!),returns(closes.get(symbols[j])!));correlations.push({a:symbols[i],b:symbols[j],correlation:c,warning:(c??0)>=0.75})}
  const dominantFactors=Object.entries(factorExposure).sort((a,b)=>b[1].riskUsd-a[1].riskUsd).slice(0,5).map(([factor,v])=>({factor,...v,riskPct:risk.accountValueUsd>0?Number((v.riskUsd/risk.accountValueUsd*100).toFixed(2)):0}));const warnings:string[]=[];for(const d of dominantFactors)if(d.trades>=2&&d.riskUsd>risk.openRiskUsd*.45)warnings.push(`ריכוז גבוה: ${d.factor} מופיע ב-${d.trades} פוזיציות ומרכז כ-$${d.riskUsd.toFixed(0)} מהסיכון הפתוח.`);for(const c of correlations.filter(x=>x.warning))warnings.push(`קורלציה גבוהה: ${c.a} ו-${c.b} נעות יחד בקירוב ${c.correlation}.`);
  const value={generatedAt:new Date().toISOString(),risk,factorExposure,dominantFactors,correlations,warnings,recordedTrades:trades.map(t=>({symbol:t.symbol,riskUsd:t.riskUsd,riskPct:t.riskPct,factors:factorRows.get(t.symbol)??["UNCLASSIFIED"]}))};cache={at:Date.now(),value};return value}
export function factorsForSymbol(symbol:string){return factors(symbol)}
