import type { MarketRegime, StrategyOpportunity, StrategyOpportunitySnapshot, TradePlan } from "@trader-os/shared";
import { dataPath, isoNow, readJsonFile, writeJsonFile } from "./store.js";
import { getTraderBrain } from "./brain.js";
import { getEventCalendar } from "./calendar.js";
import { getDecisionJournal, journalMetrics, recordStrategyOpportunityDecision } from "./journal.js";
import { getPortfolioIntelligence } from "./portfolio-intelligence.js";
import { getActiveTrades, getClosedTrades, portfolioRiskSummary } from "./portfolio.js";
import { runMarketScan } from "./trader.js";
import { getNewsSignal, type NewsSignal } from "./news.js";
import { assessCatalyst } from "./catalyst.js";
import { playbookHe, regimeHe, rsHe, sectorHe, statusHe, trendHe, verdictHe } from "./i18n-he.js";
import { evaluatePreTradeGate, type PreTradeGateResult } from "./pretrade-gate.js";
import { buildAdvancedDecision, calibrationSnapshot, opportunityCost } from "./reasoning-engine.js";
import { recordRankingSnapshot } from "./ranking-stability.js";
import { deriveMarketPhase } from "./market-state-machine.js";

const RULESET_VERSION="3.0.2-deep-coverage";
const MIN_OPPORTUNITY_SCORE=Math.max(5,Math.min(9,Number(process.env.MIN_OPPORTUNITY_SCORE??6.5)));
const MIN_OPPORTUNITY_DATA_QUALITY=Math.max(60,Math.min(100,Number(process.env.MIN_OPPORTUNITY_DATA_QUALITY??75)));
const MIN_OPPORTUNITY_RR=Math.max(1.5,Math.min(4,Number(process.env.MIN_OPPORTUNITY_RR??2)));
const oppPath=dataPath("strategy-opportunities.json");
const briefPath=dataPath("market-brief-deterministic.json");

function grade(confidence:number):StrategyOpportunity["grade"]{return confidence>=90?"A+":confidence>=82?"A":confidence>=74?"B+":confidence>=65?"B":"PASS"}
function regimeRisk(regime?:MarketRegime){return regime==="RISK_OFF"?"השוק הרחב במצב הגנתי (Risk-Off)":regime==="HIGH_VOL"?"התנודתיות בשוק גבוהה":regime==="CHOP"?"השוק מדשדש ועלול להעניש פריצות חלשות":regime==="TREND_DOWN"?"מגמת השוק הרחבה יורדת":"אין כרגע אזהרת משטר שוק משמעותית"}
function technicalReason(p:TradePlan){const t=p.technicals,parts:string[]=[];if(t?.trend)parts.push(trendHe[t.trend]??t.trend);if(t?.timeframeAlignmentPct!=null)parts.push(`התאמת טווחי זמן ${t.timeframeAlignmentPct}%`);if(t?.relativeVolume!=null)parts.push(`נפח יחסי ${t.relativeVolume}x`);if(t?.rsi14!=null)parts.push(`RSI ${t.rsi14}`);if(p.context?.sectorAlignment)parts.push(sectorHe[p.context.sectorAlignment]??p.context.sectorAlignment);return parts.join(" · ")||"המידע הטכני עדיין חלקי"}
function confidenceFor(p:TradePlan,news?:NewsSignal){let c=p.convictionScore??Math.round(p.setupScore*10);const q=p.dataQualityPct??0,rr=p.riskReward??0,mtf=p.technicals?.timeframeAlignmentPct??0,rvol=p.technicals?.relativeVolume??0;
  if(q>=95)c+=3;else if(q<70)c-=20;const dc=p.dataConfidenceScore??100;if(dc>=90)c+=4;else if(dc<70)c-=14;if(p.secCriticalRisk)c-=30;if((p.spreadPct??0)>.8)c-=12;if((p.fundamentalHealthScore??50)>=75)c+=2;else if((p.fundamentalHealthScore??50)<30)c-=3;if(rr>=3)c+=4;else if(rr>0&&rr<2)c-=15;if(mtf>=75)c+=5;else if(mtf<50)c-=8;if(rvol>=1.5)c+=4;else if(rvol>0&&rvol<1)c-=5;
  if(p.context?.sectorAlignment==="TAILWIND")c+=4;if(p.context?.sectorAlignment==="HEADWIND")c-=8;if(p.context?.relativeStrengthGrade==="LEADER")c+=6;if(p.context?.relativeStrengthGrade==="OUTPERFORM")c+=3;if(p.context?.relativeStrengthGrade==="LAGGARD")c-=8;if(p.context?.marketRegime==="RISK_ON")c+=4;if(p.context?.marketRegime==="RISK_OFF")c-=12;if(p.context?.marketRegime==="CHOP")c-=5;if(p.eventRiskLocked)c-=25;if(p.technicals?.abnormalVolume)c+=3;if((p.technicals?.priceExpansionAtr??0)>=3)c-=8;
  if(p.notes?.includes("NO CHASE"))c-=20;if(news?.tone==="POSITIVE")c+=3;if(news?.tone==="NEGATIVE")c-=6;if(news?.criticalNegative)c-=25;return Math.max(0,Math.min(100,Math.round(c)))}
function qualityRejectReasons(p:TradePlan,gate:PreTradeGateResult){
 const reasons:string[]=[];
 if((p.dataQualityPct??0)<MIN_OPPORTUNITY_DATA_QUALITY)reasons.push(`איכות הנתונים ${p.dataQualityPct??0}% נמוכה מהרף ${MIN_OPPORTUNITY_DATA_QUALITY}%`);
 if((p.dataConfidenceScore??100)<Number(process.env.MIN_DATA_CONFIDENCE_SCORE??70))reasons.push(`אמינות המידע ${p.dataConfidenceScore??0}% נמוכה מהרף`);
 if(p.secCriticalRisk)reasons.push("דיווח SEC טרי מפעיל חסימת סיכון");
 if(p.spreadPct!==undefined&&p.spreadPct>Number(process.env.MAX_EXECUTION_SPREAD_PCT??0.8))reasons.push(`הספרד רחב מדי (${p.spreadPct.toFixed(2)}%)`);
 if(!p.playbook||p.playbook==="NONE")reasons.push("לא זוהתה תבנית מסחר שאנחנו יודעים לבצע בצורה עקבית");
 if(!p.entry||!p.stop||!p.tp1||!p.tp2)reasons.push("אין סט מלא של כניסה, סטופ ויעדים");
 if(p.levelQuality==="NONE")reasons.push("מנוע הרמות לא הצליח לבנות רמות אמינות לתבנית");
 if((p.riskReward??0)<MIN_OPPORTUNITY_RR)reasons.push(`יחס הסיכוי/סיכון נמוך מ-1:${MIN_OPPORTUNITY_RR}`);
 if(p.setupScore<MIN_OPPORTUNITY_SCORE)reasons.push(`ציון העסקה ${p.setupScore}/10 נמוך מהרף ${MIN_OPPORTUNITY_SCORE}/10`);
 if((p.technicals?.averageDollarVolume20d??20_000_000)>0&&(p.technicals?.averageDollarVolume20d??20_000_000)<5_000_000)reasons.push("נזילות דולרית נמוכה מדי");
 if(gate.verdict==="NO_ENTRY")reasons.push(...gate.blockers.slice(0,3));
 return[...new Set(reasons)]
}
function opportunityFromPlan(p:TradePlan,news:NewsSignal|undefined,gate:PreTradeGateResult):StrategyOpportunity{
 const confidence=confidenceFor(p,news),quality=p.dataQualityPct??0,rr=p.riskReward??0,rejectionReasons=qualityRejectReasons(p,gate);let verdict:StrategyOpportunity["verdict"]="WATCH";
 if(rejectionReasons.length)verdict="REJECT";
 else if(gate.verdict==="ENTER"&&p.entry&&p.stop&&rr>=MIN_OPPORTUNITY_RR&&confidence>=78&&!p.dataFlags?.includes("DEEP_CACHE_REUSED"))verdict="READY";
 else if((!gate.gates.marketOpen||p.dataFlags?.includes("DEEP_CACHE_REUSED")||p.status==="ARMED")&&p.entry&&p.stop&&rr>=MIN_OPPORTUNITY_RR&&confidence>=70)verdict="ARMED";
 const headline=verdict==="READY"?`${p.symbol} עברה את כל תנאי הכניסה`:verdict==="ARMED"?`${p.symbol} מוכנה וממתינה לטריגר`:verdict==="REJECT"?`${p.symbol} נפסלה מרשימת ההזדמנויות`:`${p.symbol} איכותית מספיק למעקב, אך עדיין אינה מוכנה`;
 const positiveHeadline=news?.items.find(x=>x.tone==="POSITIVE")?.headline;const negativeHeadline=news?.items.find(x=>x.tone==="NEGATIVE")?.headline;const cs=assessCatalyst(p,news);
 const catalyst=positiveHeadline?`כותרת חיובית: ${positiveHeadline}`:cs.drivers.length?`${cs.label}: ${cs.drivers.join(", ")}`:p.playbook&&p.playbook!=="NONE"?`תבנית טכנית: ${playbookHe[p.playbook]}`:"עדיין לא זוהה קטליזטור ברור";
 const keyRisk=verdict==="REJECT"?(rejectionReasons[0]??"לא עברה את רף האיכות"):news?.criticalNegative&&negativeHeadline?`סיכון חדשותי קריטי: ${negativeHeadline}`:p.eventRiskLocked?"קיימת חסימת סיכון אירוע":news?.tone==="NEGATIVE"&&negativeHeadline?`כותרת שלילית: ${negativeHeadline}`:p.context?.relativeStrengthGrade==="LAGGARD"?"המניה חלשה יחסית לשוק ולסקטור":p.context?.sectorAlignment==="HEADWIND"?`הסקטור ${p.context.sectorEtf??""} מהווה רוח נגדית`:regimeRisk(p.context?.marketRegime);
 const rs=p.context?.relativeStrengthGrade?rsHe[p.context.relativeStrengthGrade]:"לא ידוע";
 return{symbol:p.symbol,confidence,grade:grade(confidence),verdict,setupScore:p.setupScore,convictionScore:p.convictionScore,playbook:p.playbook,headline,rationale:`${technicalReason(p)}. חוזק יחסי: ${rs}. איכות נתונים: ${quality}%. אמינות מידע: ${p.dataConfidenceScore??"—"}%. ${p.thesis}`,catalyst,keyRisk,entry:p.entry,stop:p.stop,tp1:p.tp1,tp2:p.tp2,riskReward:p.riskReward,dataQualityPct:p.dataQualityPct,eventRiskLocked:p.eventRiskLocked,relativeStrengthGrade:p.context?.relativeStrengthGrade,sectorEtf:p.context?.sectorEtf,sectorKnown:Boolean(p.context?.sectorEtf),learningAdjustment:p.learningAdjustment,catalystScore:cs.score,dataAsOf:p.dataAsOf??isoNow(),levelQuality:p.levelQuality,entryLogic:p.entryLogic,stopLogic:p.stopLogic,targetLogic:p.targetLogic,rejectionReasons,dataConfidenceScore:p.dataConfidenceScore,dataConfidenceGrade:p.dataConfidenceGrade,spreadPct:p.spreadPct,securityExchange:p.securityExchange,securitySector:p.securitySector,fundamentalHealthScore:p.fundamentalHealthScore,secCriticalRisk:p.secCriticalRisk}
}

async function rankStrategyOpportunitiesInternal(force=true,record=true):Promise<StrategyOpportunitySnapshot>{
  const scan=await runMarketScan(force),news=await Promise.all(scan.candidates.slice(0,8).map(p=>getNewsSignal(p.symbol,force))),newsMap=new Map(news.map(x=>[x.symbol,x])),opportunities:StrategyOpportunity[]=[];
  for(const p of scan.candidates){const n=newsMap.get(p.symbol),cs=assessCatalyst(p,n),gate=evaluatePreTradeGate(p,scan.market.status,{headlineCritical:n?.criticalNegative,catalystBlocked:cs.blocksEntry});opportunities.push(opportunityFromPlan({...p,verdict:gate.verdict,portfolioGatePassed:gate.gates.portfolioCapacity&&gate.gates.sectorCapacity,portfolioGateReason:gate.blockers.find(x=>x.includes("תיק")||x.includes("סקטור"))},n,gate))}
  opportunities.sort((a,b)=>{const rank=(v:string)=>v==="READY"?4:v==="ARMED"?3:v==="WATCH"?2:1;return rank(b.verdict)-rank(a.verdict)||b.confidence-a.confidence||b.setupScore-a.setupScore});
  recordRankingSnapshot(opportunities,scan.scanId);
  const planMap=new Map(scan.candidates.map(p=>[p.symbol,p]));
  // Evidence-driven committee: all visible candidates get core reasoning; the strongest five also receive free external context (FINRA/Nasdaq/options/corporate actions).
  for(let i=0;i<Math.min(opportunities.length,12);i++){const o=opportunities[i],p=planMap.get(o.symbol);if(!p)continue;try{const decision=await buildAdvancedDecision(p,o.confidence,i<5);o.advancedDecision=decision;o.confidence=Math.round(decision.calibratedProbability??o.confidence);o.grade=grade(o.confidence);if(decision.judgeVerdict==="REJECT")o.verdict="REJECT";else if(decision.judgeVerdict==="UNCERTAIN"&&o.verdict!=="REJECT")o.verdict="WATCH";else if(decision.judgeVerdict==="ARMED"&&o.verdict!=="REJECT")o.verdict="ARMED";else if(decision.judgeVerdict==="ENTER"&&o.verdict!=="REJECT")o.verdict=scan.market.status==="OPEN"&&!p.dataFlags?.includes("DEEP_CACHE_REUSED")?"READY":"ARMED"}catch{}}
  opportunities.sort((a,b)=>{const rank=(v:string)=>v==="READY"?4:v==="ARMED"?3:v==="WATCH"?2:1;return rank(b.verdict)-rank(a.verdict)||b.confidence-a.confidence||b.setupScore-a.setupScore});
  const rejected=opportunities.filter(x=>x.verdict==="REJECT").sort((a,b)=>b.confidence-a.confidence),visible=opportunities.filter(x=>x.verdict!=="REJECT"),top=visible.slice(0,12),ready=top.filter(x=>x.verdict==="READY").length,armed=top.filter(x=>x.verdict==="ARMED").length,cost=opportunityCost(top),cal=calibrationSnapshot(),snapshot:StrategyOpportunitySnapshot={generatedAt:isoNow(),scanId:scan.scanId,reused:(scan as any).reused===true,cooldownRemainingSeconds:(scan as any).cooldownRemainingSeconds,stats:{...scan.stats},engine:"DETERMINISTIC",rulesetVersion:RULESET_VERSION,marketBias:scan.marketContext.bias,marketRegime:scan.marketContext.regime,summary:`דירוג ${scan.scanId}: Discovery כיסה ${scan.stats.fullMarketCoveragePct??0}% מהקטלוג (${scan.stats.fullMarketChecked??0}/${scan.stats.fullMarketCatalogSize??0}) — זה Quote/Snapshot ולא ניתוח עסקה מלא. בריצה הזו ${scan.stats.shortlisted} מניות חדשות עברו Deep Analysis; מאגר הניתוחים הטריים שמדורג כעת כולל ${scan.candidates.length} מניות. מתוכן ${ready} READY לביצוע עכשיו, ${armed} ARMED/ממתינות לטריגר או לפתיחת השוק, ו-${rejected.length} נפסלו. ${(scan.stats.fullMarketCoveragePct??0)<100?"Discovery עדיין לא השלים את כל הקטלוג.":"Discovery השלים סבב קטלוג מלא."}`,opportunities:top,rejected:rejected.slice(0,30),opportunityCost:cost as any,calibration:cal as any,diagnostics:[scan.summary,`מסווג חדשות: ${news.filter(x=>x.available).length}/${news.length} זמינים`,`Evidence committee: ${opportunities.filter(x=>x.advancedDecision).length} מועמדות קיבלו reasoning דטרמיניסטי`,...scan.errors.slice(0,3)]};
  writeJsonFile(oppPath,snapshot);if(record){for(const o of top.slice(0,6))recordStrategyOpportunityDecision(o,scan.marketContext.bias,scan.marketContext.regime);for(const o of rejected.slice(0,4))recordStrategyOpportunityDecision(o,scan.marketContext.bias,scan.marketContext.regime)}return snapshot
}
let rankingInFlight:Promise<StrategyOpportunitySnapshot>|null=null;
export async function rankStrategyOpportunities(force=true,record=true):Promise<StrategyOpportunitySnapshot>{if(rankingInFlight)return rankingInFlight;rankingInFlight=rankStrategyOpportunitiesInternal(force,record);try{return await rankingInFlight}finally{rankingInFlight=null}}
export function getCachedStrategyOpportunities(){return readJsonFile<StrategyOpportunitySnapshot|null>(oppPath,null)}

function bestSectorLines(plans:TradePlan[]){const agg=new Map<string,{count:number;score:number}>();for(const p of plans){const s=p.context?.sectorEtf;if(!s)continue;const x=agg.get(s)??{count:0,score:0};x.count++;x.score+=p.setupScore;agg.set(s,x)}return[...agg.entries()].map(([sector,v])=>({sector,count:v.count,avgScore:Number((v.score/v.count).toFixed(1))})).sort((a,b)=>b.avgScore-a.avgScore).slice(0,5)}
export async function buildDeterministicMarketBrief(force=true){const scan=await runMarketScan(force),calendar=await getEventCalendar(),risk=portfolioRiskSummary(),top=scan.candidates.filter(x=>(x.dataQualityPct??0)>=MIN_OPPORTUNITY_DATA_QUALITY&&(x.dataConfidenceScore??100)>=Number(process.env.MIN_DATA_CONFIDENCE_SCORE??70)&&!x.secCriticalRisk&&x.playbook!=="NONE"&&Boolean(x.entry&&x.stop&&x.tp1&&x.tp2)&&x.levelQuality!=="NONE"&&(x.riskReward??0)>=MIN_OPPORTUNITY_RR&&x.setupScore>=MIN_OPPORTUNITY_SCORE).slice(0,5),sectors=bestSectorLines(scan.candidates),events=[...calendar.earnings,...calendar.macro].filter(e=>(e.minutesAway??999999)>=0).sort((a,b)=>(a.minutesAway??0)-(b.minutesAway??0)).slice(0,8),warnings:string[]=[];if(scan.marketContext.regime==="RISK_OFF")warnings.push("השוק במצב Risk-Off: מעלים משמעותית את הרף לעסקאות לונג חדשות.");if(scan.marketContext.regime==="CHOP")warnings.push("השוק מדשדש: פריצות גבוליות מקבלות איכות נמוכה יותר.");if(risk.remainingPct<0.5)warnings.push("קיבולת הסיכון בתיק כמעט מלאה.");if(events.some(e=>e.blocksEntry))warnings.push("קיימת כרגע חסימת סיכון אירוע פעילה.");const marketPhase=deriveMarketPhase({regime:scan.marketContext.regime,breadthAdvancePct:scan.marketContext.breadth?.advancePct,avgChangePct:scan.marketContext.breadth?.avgChangePct});const text=[`מצב שוק: ${scan.market.status} · ${marketPhase.labelHe} · הטיה ${scan.marketContext.bias} · ${regimeHe[scan.marketContext.regime??"UNKNOWN"]} (ציון ${scan.marketContext.regimeScore??0}).`,`רוחב Universe הסריקה: ${scan.marketContext.breadth?.advancePct??0}% מהמניות עולות; שינוי ממוצע ${scan.marketContext.breadth?.avgChangePct??0}%.`,`המועמדות המובילות: ${top.map(x=>`${x.symbol} ${x.setupScore}/10 · ${rsHe[x.context?.relativeStrengthGrade??"UNKNOWN"]} · ${statusHe[x.status]??x.status}`).join(", ")||"אין"}.`,`סיכון תיק: ${risk.usedPct}% מתוך ${risk.maxPct}% מנוצל; נשארו ${risk.remainingPct}% קיבולת סיכון.`,warnings.length?`אזהרות: ${warnings.join(" ")}`:"אין כרגע אזהרת שוק/תיק שחוצה את סף החסימה."].join("\n");const value={generatedAt:isoNow(),engine:"DETERMINISTIC",rulesetVersion:RULESET_VERSION,session:scan.market.status,marketPhase,marketBias:scan.marketContext.bias,marketRegime:scan.marketContext.regime,regimeScore:scan.marketContext.regimeScore,regimeReasons:scan.marketContext.regimeReasons,breadth:scan.marketContext.breadth,sectors,topSetups:top,eventRisks:events,risk,warnings,text};writeJsonFile(briefPath,value);return value}
export function getCachedMarketBrief(){return readJsonFile<any>(briefPath,{generatedAt:null,engine:"DETERMINISTIC",text:"יש לרענן את תמונת השוק כדי לקבל סיכום עדכני."})}

export function deterministicCoachReview(){const metrics=journalMetrics(),closed=getClosedTrades(),done=closed.filter(x=>typeof x.realizedR==="number"&&!(x.closureSource==="LEVEL_MONITOR"&&x.brokerExecutionConfirmed===false)),wins=done.filter(x=>(x.realizedR??0)>0),adherence=closed.filter(x=>x.followedPlan===true).length,violations=closed.filter(x=>x.followedPlan===false).length,avgR=done.length?Number((done.reduce((s,x)=>s+(x.realizedR??0),0)/done.length).toFixed(2)):0;const by=Object.entries(metrics.byPlaybook??{}).sort((a:any,b:any)=>b[1].avgR-a[1].avgR),best=by[0],worst=by.at(-1),recommendations:string[]=[];
  if(done.length<10)recommendations.push("המדגם עדיין קטן; עדיף להתמקד בעקביות בביצוע ולא לנסות לבצע אופטימיזציה מוקדמת.");if(avgR<0)recommendations.push("ממוצע ה-R הממומש שלילי; צריך להחמיר את סינון הכניסות לפני שמגדילים סיכון.");if(violations>adherence)recommendations.push("העמידה בתוכנית חלשה; המשימה הראשונה היא לשפר משמעת בסטופ וביעדים.");if(best&&((best[1] as any).count??0)>=3)recommendations.push(`התבנית החזקה ביותר במדגם: ${playbookHe[best[0]]??best[0]} עם ממוצע ${(best[1] as any).avgR}R.`);if(worst&&((worst[1] as any).count??0)>=3&&(worst[1] as any).avgR<0)recommendations.push(`כדאי לצמצם או לבחון מחדש עסקאות מסוג ${playbookHe[worst[0]]??worst[0]}; הממוצע שנמדד הוא ${(worst[1] as any).avgR}R.`);if(!recommendations.length)recommendations.push("לא זוהתה כרגע אזהרת ביצוע משמעותית לפי כללי האימון הדטרמיניסטיים.");return{generatedAt:isoNow(),engine:"DETERMINISTIC",metrics:{...metrics,closedTrades:closed.length,measuredTrades:done.length,wins:wins.length,avgRealizedR:avgR,planAdherencePct:closed.length?Number((adherence/closed.length*100).toFixed(1)):0},recommendations,latestDecisions:getDecisionJournal(20)}}
export function getStrategyEngineStatus(){const brain=getTraderBrain();return{engine:"DETERMINISTIC",externalAi:false,model:null,modelCostUsd:0,rulesetVersion:RULESET_VERSION,brainVersion:brain.version,capabilities:["Bull/Bear/Judge evidence committee","historical analogs + probability calibration","contradiction/anomaly/freshness engines","ranking stability + opportunity cost + stress test","FINRA short context + SEC FTD + Nasdaq halt/Reg SHO guards","Alpaca corporate actions + indicative options context","full-US catalog sweep with optional free Alpaca IEX bulk snapshots","rich market regime/breadth scoring","dynamic SEC-backed security master and sector/industry classification","multi-window relative strength vs SPY/sector","multi-timeframe analysis","abnormal volume/price detection","parallel playbook-specific scanners and structural level engine","deterministic catalyst engine + SEC filings risk","SEC XBRL fundamentals + local historical warehouse + walk-forward backtesting","event-risk gate","portfolio-risk gate","position sizing","live WebSocket prices","automatic level monitor","manual trade entry","trigger engine","trade management","decision journal","shadow trading","strategy console","self-explaining UI"],limitations:["אין reasoning גנרטיבי חופשי — ההחלטות מבוססות חוקים ונתונים","חדשות מסווגות דטרמיניסטית מספק הנתונים ואינן מפוענחות כמו מודל שפה","לוח המאקרו נמשך ומפוענח מדפי BLS/Federal Reserve עם cache; אם הפענוח נכשל נשמר fallback וניתן להוסיף אירוע ידני","סריקת כל קטלוג המניות היא רציפה ומבוקרת מכסה; ניתוח OHLCV עמוק מבוצע רק לפיינליסטיות ולא לכל השוק בו-זמנית","מיפוי סקטור דינמי נגזר מ-SEC SIC; כאשר הסיווג אינו חד-משמעי הוא נשאר לא מסווג במקום להמציא Tailwind/Headwind","Alpaca Basic החינמי משתמש ב-IEX בלבד ולכן אינו תחליף ל-SIP/NBBO מלא; הוא משמש שכבת אימות/האצה ולא מקור אמת בלעדי","אין עדיין סנכרון ביצועים חי מול IBI או Web Push מרוחק מלא; סגירות אוטומטיות לפי רמות הן סגירות Tracker ולא אישור Fill מהברוקר"]}}
