import type { ActiveTrade } from "@trader-os/shared";
import { getActiveTrades } from "./portfolio.js";
import { checkEntry, getQuote } from "./trader.js";
import { getLivePrice } from "./live-prices.js";
import { dataPath, isoNow, readJsonFile, writeJsonFile } from "./store.js";

export interface ThesisMonitorResult {tradeId:string;symbol:string;at:string;status:"VALID"|"WEAKENING"|"INVALIDATED"|"UNKNOWN";score:number;currentPrice?:number;reasons:string[];changes:string[];recommendedAction:string;freshCheck?:any}
const path=dataPath("thesis-monitor.json");
function load(){return readJsonFile<Record<string,ThesisMonitorResult>>(path,{})}
function save(x:ThesisMonitorResult){const s=load();s[x.tradeId]=x;writeJsonFile(path,s);return x}
export function getThesisMonitorCache(){return load()}

export async function monitorTradeThesis(trade:ActiveTrade,deep=true):Promise<ThesisMonitorResult>{const prev=load()[trade.id],reasons:string[]=[],changes:string[]=[];let price=getLivePrice(trade.symbol)?.price;try{if(!price)price=(await getQuote(trade.symbol)).price}catch{}let score=75,status:ThesisMonitorResult["status"]="VALID",fresh:any=undefined;if(price&&trade.stop){const stopHit=trade.side==="LONG"?price<=trade.stop:price>=trade.stop;if(stopHit){status="INVALIDATED";score=0;reasons.push("המחיר חצה את הסטופ שהוגדר לעסקה.")}}if(status!=="INVALIDATED"&&deep){try{const c=await checkEntry(trade.symbol);fresh=c;const s=c.setup;if(s){if(s.context?.marketRegime==="RISK_OFF"){score-=18;reasons.push("מצב השוק עבר ל-Risk-Off.")}if(s.context?.sectorAlignment==="HEADWIND"){score-=15;reasons.push("הסקטור הפך לרוח נגדית.")}if(s.context?.relativeStrengthGrade==="LAGGARD"){score-=15;reasons.push("המניה הפכה לחלשה יחסית לשוק/סקטור.")}if((s.technicals?.relativeVolume??1)<.8){score-=10;reasons.push("הנפח היחסי נחלש משמעותית.")}if((s.dataConfidenceScore??100)<70){score-=20;reasons.push("אמינות המידע ירדה מתחת לרף הבטוח.")}if(s.secCriticalRisk){status="INVALIDATED";score=0;reasons.push("נמצא Filing SEC קריטי חדש שמחייב Validation מחדש.")}if(c.verdict==="NO_ENTRY"&&status!=="INVALIDATED"){score-=10;reasons.push("בדיקת כניסה חדשה כבר אינה עוברת את כל ה-Gates.")}}}catch(e){score-=8;reasons.push("לא ניתן היה להשלים Validation עמוק כרגע; נשארים זהירים.")}}
  if(status!=="INVALIDATED"){if(score<40)status="INVALIDATED";else if(score<65)status="WEAKENING";else status="VALID"}if(prev){if(prev.status!==status)changes.push(`מצב התזה השתנה מ-${prev.status} ל-${status}.`);if(prev.currentPrice&&price){const p=(price/prev.currentPrice-1)*100;if(Math.abs(p)>.5)changes.push(`המחיר השתנה ${p>0?"+":""}${p.toFixed(1)}% מאז בדיקת התזה הקודמת.`)}}if(!changes.length)changes.push("לא זוהה שינוי מהותי מאז בדיקת התזה הקודמת.");const recommendedAction=status==="INVALIDATED"?"פתח את חדר העסקה מיד. אם הסטופ/תנאי הביטול התקיימו, פעל לפי התוכנית ואל תרחיב סיכון.":status==="WEAKENING"?"אל תגדיל פוזיציה. בדוק אם נדרש הידוק סיכון/מימוש לפי התוכנית המקורית.":"התזה עדיין תקפה. המשך לעקוב אחרי Stop/TP ואל תשנה תוכנית ללא סיבה חדשה.";return save({tradeId:trade.id,symbol:trade.symbol,at:isoNow(),status,score:Math.max(0,Math.min(100,Math.round(score))),currentPrice:price,reasons:reasons.length?reasons:["לא נמצא כרגע סימן מהותי שמבטל את התזה."],changes,recommendedAction,freshCheck:fresh})}
export async function monitorAllOpenTradeTheses(deep=true){const rows:ThesisMonitorResult[]=[];for(const t of getActiveTrades().filter(x=>x.executionState==="RECORDED").slice(0,5)){try{rows.push(await monitorTradeThesis(t,deep))}catch{}}return{generatedAt:isoNow(),rows}}
