import type { DashboardSnapshot, MarketBreadth, MarketContext, MarketQuote, MarketRegime, TradePlan, TraderProfile } from "@trader-os/shared";
import { analyzeLongSetup } from "./analytics.js";
import { eventRisksFor, refreshEarningsCalendar } from "./calendar.js";
import { createMarketDataProvider } from "./market-data.js";
import { recordTradePlanDecision } from "./journal.js";
import { getActiveTrades, getWatchlist, getClosedTrades, portfolioRiskSummary } from "./portfolio.js";
import { getNewsSignal } from "./news.js";
import { assessCatalyst } from "./catalyst.js";
import { learningAdjustmentFor } from "./learning.js";
import { explainEntryHe, regimeHe } from "./i18n-he.js";
import { evaluatePreTradeGate } from "./pretrade-gate.js";
import { storageStatus } from "./store.js";
import { getScannerCoverage, prepareDiscoveryBatch, recordDiscoveryLeaders } from "./scanner-universe.js";
import { addLiveSymbols, seedLiveQuote } from "./live-prices.js";
import { advanceFullMarketSweep, getFullMarketCandidates, getFullMarketSweepStatus, resetFullMarketSweep, takeFullMarketFinalists } from "./full-market-scan.js";
import { alpacaFreeStatus, getAlpacaSnapshots } from "./alpaca-free.js";
import { buildDataConfidence } from "./data-confidence.js";
import { getSecurityIdentity, getSecCompanyIntelligence } from "./sec-intelligence.js";
import { getWarehouseBars, recordDeepAnalysisBars, syncDailyHistoryFree, upsertWarehouseBars } from "./market-warehouse.js";
import { scorePlaybookSignals } from "./playbook-scanners.js";
import { buildAdvancedDecision } from "./reasoning-engine.js";
import { getDeepCandidateCacheStatus, mergeDeepCandidateCache } from "./deep-candidate-cache.js";

export const traderProfile: TraderProfile = { style:"day_swing",holdingPeriod:"1-3d",riskProfile:"conservative",capitalPreservationFirst:true,noChasing:true,requireDefinedStop:true,requireRiskReward:true };
const provider=createMarketDataProvider();
const DEFAULT_UNIVERSE=["NVDA","AMD","TSLA","AAPL","AMZN","META","MSFT","GOOGL","AVGO","PLTR","MU","SMCI","ARM","ANET","CRWD","ORCL","DELL","WDC","INTC","QCOM","BA","CAT","GE","UBER","COIN","HOOD","RKLB","ASTS","SOFI","RIVN","F","GM","NKE","CROX","MARA","RIOT","CCL","RCL","UAL","DAL"];
const DEFAULT_SECTOR_MAP:Record<string,string>={NVDA:"XLK",AMD:"XLK",AAPL:"XLK",MSFT:"XLK",AVGO:"XLK",PLTR:"XLK",MU:"XLK",SMCI:"XLK",ARM:"XLK",ANET:"XLK",CRWD:"XLK",ORCL:"XLK",DELL:"XLK",WDC:"XLK",INTC:"XLK",QCOM:"XLK",TSLA:"XLY",AMZN:"XLY",NKE:"XLY",CROX:"XLY",CCL:"XLY",RCL:"XLY",META:"XLC",GOOGL:"XLC",BA:"XLI",CAT:"XLI",GE:"XLI",UBER:"XLI",RKLB:"XLI",ASTS:"XLI",UAL:"XLI",DAL:"XLI",COIN:"XLF",HOOD:"XLF",SOFI:"XLF",RIVN:"XLY",F:"XLY",GM:"XLY",MARA:"XLK",RIOT:"XLK"};
function parseSymbols(raw:string|undefined){return(raw??"").split(",").map(x=>x.trim().toUpperCase()).filter(Boolean)}
const configuredUniverse=parseSymbols(process.env.SCAN_UNIVERSE),legacyPriority=parseSymbols(process.env.SCAN_SYMBOLS),scanUniverse=[...new Set([...(configuredUniverse.length?configuredUniverse:DEFAULT_UNIVERSE),...legacyPriority])].slice(0,120),marketSymbols=parseSymbols(process.env.MARKET_SYMBOLS??"SPY,QQQ,IWM").slice(0,10);
const scanCacheMs=Math.max(15_000,Number(process.env.MARKET_SCAN_CACHE_MS??60_000));
const candleResolution=process.env.CANDLE_RESOLUTION??"5",lookbackDays=Math.max(2,Math.min(30,Number(process.env.SCAN_LOOKBACK_DAYS??7))),shortlistSize=Math.max(3,Math.min(16,Number(process.env.SCAN_SHORTLIST_SIZE??8))),deepAnalysisMax=Math.max(2,Math.min(shortlistSize,Number(process.env.DEEP_ANALYSIS_MAX_SYMBOLS??3))),fullMarketFinalistSlots=Math.max(0,Math.min(deepAnalysisMax-1,Number(process.env.FULL_MARKET_FINALIST_DEEP_SLOTS??1))),minPrice=Math.max(0,Number(process.env.SCAN_MIN_PRICE??5)),maxPrice=Math.max(minPrice,Number(process.env.SCAN_MAX_PRICE??1000)),discoveryConcurrency=Math.max(1,Math.min(12,Number(process.env.SCAN_DISCOVERY_CONCURRENCY??8))),quoteBudget=Math.max(20,Math.min(60,Number(process.env.SCAN_QUOTE_BUDGET??process.env.SCAN_UNIVERSE_MAX??48))),rotationBatchSize=Math.max(8,Math.min(50,Number(process.env.ROTATING_SCAN_BATCH_SIZE??36))),explorationSlots=Math.max(0,Math.min(deepAnalysisMax-1,Number(process.env.DEEP_EXPLORATION_SLOTS??1))),scanCooldownMs=Math.max(10_000,Number(process.env.MANUAL_SCAN_COOLDOWN_SECONDS??45)*1000);
function parseSectorMap(){const map=new Map<string,string>(Object.entries(DEFAULT_SECTOR_MAP));const raw=String(process.env.SECTOR_MAP??"");for(const pair of raw.split(",").map((x:string)=>x.trim()).filter(Boolean)){const[s,e]=pair.split(":").map((x:string)=>x.trim().toUpperCase());if(s&&e)map.set(s,e)}return map}const sectorMap=parseSectorMap();
const demoOpportunities:TradePlan[]=[{symbol:"ASTS",side:"LONG",status:"WATCHING",verdict:"WAIT",setupScore:0,holdingPeriod:"1-3d",thesis:"ספק נתוני השוק עדיין לא מוגדר.",trigger:"יש להגדיר FINNHUB_API_KEY בקובץ .env ולהפעיל מחדש את הקונטיינר.",notes:["DEMO DATA"],dataQualityPct:0}];
function ageSeconds(timestamp?:string){if(!timestamp)return undefined;const ms=Date.parse(timestamp);return Number.isFinite(ms)?Math.max(0,Math.floor((Date.now()-ms)/1000)):undefined}


function returnWindow(bars:{close:number}[],n:number){if(bars.length<=n)return undefined;const a=bars.at(-(n+1))?.close,b=bars.at(-1)?.close;return a&&b?((b/a)-1)*100:undefined}
async function ensureDailyWarehouse(symbol:string){const sym=symbol.toUpperCase();let bars=getWarehouseBars(sym,"1d",5000);if(bars.length>=60)return bars;if(alpacaFreeStatus().configured){try{await syncDailyHistoryFree(sym,5,false);bars=getWarehouseBars(sym,"1d",5000);if(bars.length>=60)return bars}catch{}}
 try{const now=Math.floor(Date.now()/1000),daily=await provider.getCandles(sym,"1day",now-400*86400,now,false);upsertWarehouseBars(sym,"1d",daily,provider.candleProviderName);return daily}catch{return bars}}
async function enrichRelativeStrength(plan:TradePlan,sectorEtf?:string){if(!plan.technicals)return plan;const [stock,spy,sector]=await Promise.all([ensureDailyWarehouse(plan.symbol),ensureDailyWarehouse("SPY"),sectorEtf?ensureDailyWarehouse(sectorEtf):Promise.resolve([])]);const s1=returnWindow(stock,1),s5=returnWindow(stock,5),s20=returnWindow(stock,20),m1=returnWindow(spy,1),m5=returnWindow(spy,5),m20=returnWindow(spy,20),e5=returnWindow(sector,5),e20=returnWindow(sector,20);const t={...plan.technicals,rs1dPct:s1!==undefined&&m1!==undefined?Number((s1-m1).toFixed(2)):undefined,rs5dPct:s5!==undefined&&m5!==undefined?Number((s5-m5).toFixed(2)):undefined,rs20dPct:s20!==undefined&&m20!==undefined?Number((s20-m20).toFixed(2)):undefined,rsSector5dPct:s5!==undefined&&e5!==undefined?Number((s5-e5).toFixed(2)):undefined,rsSector20dPct:s20!==undefined&&e20!==undefined?Number((s20-e20).toFixed(2)):undefined};return{...plan,technicals:t}}
async function resolveSecurityMap(symbols:string[]){const map=new Map<string,Awaited<ReturnType<typeof getSecurityIdentity>>>();await Promise.all(symbols.map(async s=>{try{map.set(s,await getSecurityIdentity(s,false))}catch{}}));return map}
async function enrichFreeIntelligence(plan:TradePlan,identity?:Awaited<ReturnType<typeof getSecurityIdentity>>){let out={...plan};const id=identity??await getSecurityIdentity(plan.symbol,false).catch(()=>undefined);if(id){out={...out,securityExchange:id.exchange,securitySector:id.sector,securityIndustry:id.sicDescription};if(id.sectorEtf&&!sectorMap.has(plan.symbol))sectorMap.set(plan.symbol,id.sectorEtf)}out=await enrichRelativeStrength(out,id?.sectorEtf??out.context?.sectorEtf);out={...out,scannerSignals:scorePlaybookSignals(out.quote!,out.technicals)};try{const report=await buildDataConfidence(out,{includeSec:true,includeAlpaca:true}),sec=report.sec;out={...out,dataConfidenceScore:report.score,dataConfidenceGrade:report.grade,spreadPct:report.liquidity?.spreadPct,securityExchange:sec?.identity.exchange??out.securityExchange,securitySector:sec?.identity.sector??out.securitySector,securityIndustry:sec?.identity.sicDescription??out.securityIndustry,fundamentalHealthScore:sec?.fundamentals.healthScore,secCriticalRisk:sec?.criticalFilingRisk,dataFlags:[...(out.dataFlags??[]),`DATA_CONFIDENCE_${report.score}`,report.liquidity?.spreadPct!==undefined?`IEX_SPREAD_${report.liquidity.spreadPct.toFixed(2)}%`:"SPREAD_UNAVAILABLE",sec?.criticalFilingRisk?"SEC_CRITICAL_RISK":"SEC_NO_CRITICAL_RISK"]};if(report.grade==="BLOCK")out={...out,verdict:"NO_ENTRY",notes:[...(out.notes??[]),"אמינות הנתונים הכוללת נמוכה מדי לביצוע"]};if(sec?.criticalFilingRisk)out={...out,verdict:"NO_ENTRY",notes:[...(out.notes??[]),"SEC RISK LOCK: filing חדש מצביע על סיכון גיוס/דילול"]}}catch{}return out}

function usableOpportunityCandidate(x:TradePlan){const maxSpread=Number(process.env.MAX_EXECUTION_SPREAD_PCT??0.8),minConfidence=Number(process.env.MIN_DATA_CONFIDENCE_SCORE??70);return (x.dataQualityPct??0)>=75&&(x.dataConfidenceScore??100)>=minConfidence&&!x.secCriticalRisk&&(x.spreadPct===undefined||x.spreadPct<=maxSpread)&&x.playbook!=="NONE"&&Boolean(x.entry&&x.stop&&x.tp1&&x.tp2)&&x.levelQuality!=="NONE"&&(x.riskReward??0)>=2&&x.setupScore>=6.5&&x.verdict!=="NO_ENTRY"}
export function discoveryScore(q:MarketQuote){const pct=q.changePct??0,range=(q.high??0)-(q.low??0),pos=range>0&&q.low!==undefined?Math.max(0,Math.min(1,(q.price-q.low)/range)):.5,gap=q.open&&q.previousClose?((q.open-q.previousClose)/q.previousClose)*100:0;let score=Math.max(-3,Math.min(7,pct))*1.05+pos*2.2+Math.max(-1.5,Math.min(2.5,gap))*.35;if(pct>.4)score+=.45;if(pct>1.5)score+=.65;if(pct>8)score-=Math.min(3,(pct-8)*.35);if(pos>.82)score+=.35;return Number(score.toFixed(3))}
async function mapConcurrent<T,R>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<R>){const results:Array<PromiseSettledResult<R>>=new Array(items.length);let next=0;const worker=async()=>{while(true){const i=next++;if(i>=items.length)return;try{results[i]={status:"fulfilled",value:await fn(items[i],i)}}catch(reason){results[i]={status:"rejected",reason}}}};await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return results}

function buildBreadth(quotes:MarketQuote[]):MarketBreadth{const changes=quotes.map(x=>x.changePct??0),adv=changes.filter(x=>x>0).length,dec=changes.filter(x=>x<0).length,unch=changes.length-adv-dec;return{universe:changes.length,advances:adv,declines:dec,unchanged:unch,advancePct:changes.length?Number((adv/changes.length*100).toFixed(1)):0,avgChangePct:changes.length?Number((changes.reduce((a,b)=>a+b,0)/changes.length).toFixed(2)):0,strongUpPct:changes.length?Number((changes.filter(x=>x>=2).length/changes.length*100).toFixed(1)):0,strongDownPct:changes.length?Number((changes.filter(x=>x<=-2).length/changes.length*100).toFixed(1)):0}}
function deriveRegimeAssessment(ctx:MarketContext){
  const b=ctx.breadth,changes=ctx.quotes.map(x=>x.changePct??0),avgBench=changes.length?changes.reduce((a,b)=>a+b,0)/changes.length:0;
  const dispersion=changes.length?Math.max(...changes)-Math.min(...changes):0;
  let score=0; const reasons:string[]=[];
  if(b){score+=(b.advancePct-50)*1.05;score+=b.avgChangePct*14;score+=(b.strongUpPct-b.strongDownPct)*.35;if(b.advancePct>=65)reasons.push(`Breadth thrust: ${b.advancePct}% advancing`);if(b.advancePct<=35)reasons.push(`Weak breadth: ${b.advancePct}% advancing`);}
  score+=avgBench*12;score=Math.max(-100,Math.min(100,Number(score.toFixed(0))));
  const highVol=Math.abs(avgBench)>=2||dispersion>=3.2||(b?b.strongUpPct>=35||b.strongDownPct>=35:false);
  let regime:MarketRegime="UNKNOWN";
  if(highVol){regime="HIGH_VOL";reasons.push("Large benchmark/breadth dispersion signals elevated volatility");}
  else if(score>=35&&ctx.bias==="BULLISH"){regime="RISK_ON";reasons.push("Broad participation and benchmark direction are aligned bullish");}
  else if(score<=-35&&ctx.bias==="BEARISH"){regime="RISK_OFF";reasons.push("Broad participation and benchmark direction are aligned bearish");}
  else if(score>=12){regime="TREND_UP";reasons.push("Positive tape, but not a full risk-on breadth thrust");}
  else if(score<=-12){regime="TREND_DOWN";reasons.push("Negative tape, but not a full risk-off breadth collapse");}
  else {regime="CHOP";reasons.push("Mixed/low-conviction breadth suggests chop");}
  return{regime,score,reasons};
}
function deriveRegime(ctx:MarketContext):MarketRegime{return deriveRegimeAssessment(ctx).regime}

async function analyzeSymbol(symbol:string,marketStatus:DashboardSnapshot["market"]["status"],quote?:MarketQuote,fresh=true):Promise<TradePlan>{
  const now=Math.floor(Date.now()/1000),from=now-Math.max(10,lookbackDays)*86400,liveQuote=quote??await provider.getQuote(symbol,fresh),quoteAgeSeconds=ageSeconds(liveQuote.timestamp);
  try{
    const [intraday,daily]=await Promise.all([
      provider.getCandles(symbol,candleResolution,from,now,fresh),
      provider.getCandles(symbol,"1day",now-180*86400,now,fresh),
    ]);
    recordDeepAnalysisBars(symbol,intraday,daily,`${provider.candleProviderName} deep analysis`);
    const plan=analyzeLongSetup(symbol,liveQuote,intraday,marketStatus,daily),stale=marketStatus==="OPEN"&&(quoteAgeSeconds??0)>15*60,preVerified=marketStatus!=="PRE"||((quoteAgeSeconds??999999)<=120);
    let quality=98; if(stale)quality=72; if((plan.technicals?.mtfQualityPct??0)<70)quality=Math.min(quality,68); if(marketStatus==="PRE"&&!preVerified)quality=Math.min(quality,82); if(marketStatus==="AFTER")quality=Math.min(quality,90);
    return{...plan,preMarketVerified:preVerified,dataSource:`${provider.quoteProviderName} quote + ${provider.candleProviderName} intraday/daily OHLCV`,dataAsOf:liveQuote.timestamp,quoteAgeSeconds,dataQualityPct:quality,dataFlags:[`${intraday.length} intraday bars`,`${daily.length} daily bars`,`MTF_QUALITY_${plan.technicals?.mtfQualityPct??0}`,stale?"QUOTE_STALE_DURING_OPEN":"QUOTE_FRESHNESS_OK",marketStatus==="PRE"&&!preVerified?"PREMARKET_NOT_VERIFIED":"SESSION_PRICE_OK"]};
  }catch(error){return{symbol,side:"LONG",status:"WATCHING",verdict:"WAIT",setupScore:Math.max(0,Math.min(10,(liveQuote.changePct??0)>0?2:1)),playbook:"NONE",holdingPeriod:"1-3d",thesis:"המניה נמצאה בסריקה הראשונית, אבל אין כרגע אימות OHLCV מלא; לכן המערכת חוסמת חישוב של רמות כניסה, סטופ ויעדים.",trigger:provider.candlesConfigured?"ספק נתוני ה-OHLCV החזיר שגיאה או שהמכסה הסתיימה.":"יש להגדיר TWELVE_DATA_API_KEY לפני שניתן לחשב רמות ביצוע אמינות.",notes:[error instanceof Error?error.message:"OHLCV unavailable"],quote:liveQuote,dataSource:`${provider.quoteProviderName} quote`,dataAsOf:liveQuote.timestamp,quoteAgeSeconds,dataQualityPct:32,preMarketVerified:false,dataFlags:["QUOTE_ONLY","OHLCV_MISSING",provider.candlesConfigured?"CANDLE_PROVIDER_ERROR":"TWELVE_DATA_NOT_CONFIGURED"]}}
}
export async function getCurrentMarketStatus(fresh=false){if(!provider.configured)return{status:"UNKNOWN" as const};try{const s=await provider.getMarketStatus("US",fresh);return{status:s.status,exchange:s.exchange,holiday:s.holiday}}catch{return{status:"UNKNOWN" as const}}}
async function benchmarkContext(fresh=false):Promise<MarketContext>{if(!provider.configured||!marketSymbols.length)return{bias:"UNKNOWN",quotes:[]};const settled=await Promise.allSettled(marketSymbols.map(s=>provider.getQuote(s,fresh))),quotes=settled.flatMap(x=>x.status==="fulfilled"?[x.value]:[]),changes=quotes.map(x=>x.changePct).filter((x):x is number=>typeof x==="number");if(!changes.length)return{bias:"UNKNOWN",quotes};const positive=changes.filter(x=>x>0).length,negative=changes.filter(x=>x<0).length,threshold=Math.ceil(changes.length*.6),bias:MarketContext["bias"]=positive>=threshold?"BULLISH":negative>=threshold?"BEARISH":"MIXED";return{bias,quotes}}
async function getSectorQuotes(symbols:string[],fresh=false){const etfs=[...new Set(symbols.map(s=>sectorMap.get(s)).filter((x):x is string=>Boolean(x)))],settled=await Promise.allSettled(etfs.map(s=>provider.getQuote(s,fresh))),map=new Map<string,MarketQuote>();settled.forEach((x,i)=>{if(x.status==="fulfilled")map.set(etfs[i],x.value)});return map}
function contextualize(plan:TradePlan,marketContext:MarketContext,sectorQuotes:Map<string,MarketQuote>):TradePlan{
  const sectorEtf=sectorMap.get(plan.symbol),sectorQuote=sectorEtf?sectorQuotes.get(sectorEtf):undefined;
  const sec=sectorQuote?.changePct,sectorAlignment=sec===undefined?"UNKNOWN" as const:sec>.35?"TAILWIND" as const:sec<-.35?"HEADWIND" as const:"NEUTRAL" as const;
  const benchmarkChange=marketContext.quotes.length?marketContext.quotes.reduce((a,q)=>a+(q.changePct??0),0)/marketContext.quotes.length:0;
  const stockChange=plan.quote?.changePct??0;
  const relativeStrengthMarketPct=Number((stockChange-benchmarkChange).toFixed(2));
  const relativeStrengthSectorPct=sec===undefined?undefined:Number((stockChange-sec).toFixed(2));
  const rsComposite=relativeStrengthSectorPct===undefined?relativeStrengthMarketPct:(relativeStrengthMarketPct+relativeStrengthSectorPct)/2;
  const relativeStrengthGrade=rsComposite>=1?"LEADER" as const:rsComposite>=.35?"OUTPERFORM" as const:rsComposite<=-.75?"LAGGARD" as const:"NEUTRAL" as const;
  const learning=learningAdjustmentFor(plan.playbook);
  let adj=learning.adjustment;
  if(marketContext.bias==="BULLISH")adj+=.4;if(marketContext.bias==="BEARISH")adj-=.6;if(marketContext.regime==="RISK_ON")adj+=.45;if(marketContext.regime==="RISK_OFF")adj-=1;if(marketContext.regime==="CHOP")adj-=.25;
  if(sectorAlignment==="TAILWIND")adj+=.5;if(sectorAlignment==="HEADWIND")adj-=.7;if(relativeStrengthGrade==="LEADER")adj+=.65;else if(relativeStrengthGrade==="OUTPERFORM")adj+=.3;else if(relativeStrengthGrade==="LAGGARD")adj-=.8;
  if((plan.dataQualityPct??100)<60)adj-=1.25;
  let setupScore=Number(Math.max(0,Math.min(10,plan.setupScore+adj)).toFixed(1)),notes=[...(plan.notes??[])];
  if(marketContext.bias==="BEARISH")notes.push("Broader market headwind");if(sectorAlignment==="HEADWIND")notes.push(`Sector headwind (${sectorEtf})`);if(sectorAlignment==="TAILWIND")notes.push(`Sector tailwind (${sectorEtf})`);
  notes.push(`Relative strength: ${relativeStrengthGrade} (${relativeStrengthMarketPct>=0?"+":""}${relativeStrengthMarketPct}% vs market${relativeStrengthSectorPct===undefined?"":`, ${relativeStrengthSectorPct>=0?"+":""}${relativeStrengthSectorPct}% vs sector`})`);
  if(learning.sampleSize>=8&&learning.adjustment!==0)notes.push(`Adaptive playbook adjustment ${learning.adjustment>0?"+":""}${learning.adjustment} from ${learning.sampleSize} completed samples`);
  const eventRisks=eventRisksFor(plan.symbol),eventRiskLocked=eventRisks.some(e=>e.blocksEntry);if(eventRiskLocked){notes.push("EVENT RISK LOCK: imminent earnings/high-impact macro event");if(plan.verdict==="ENTER")setupScore=Math.max(0,setupScore-2)}
  const quality=plan.dataQualityPct??0,mtf=plan.technicals?.timeframeAlignmentPct??0;
  const conviction=Number(Math.max(0,Math.min(100,setupScore*7+quality*.18+mtf*.1+(sectorAlignment==="TAILWIND"?5:sectorAlignment==="HEADWIND"?-6:0)+(relativeStrengthGrade==="LEADER"?6:relativeStrengthGrade==="LAGGARD"?-7:0)+(marketContext.regime==="RISK_ON"?5:marketContext.regime==="RISK_OFF"?-10:0)-(eventRiskLocked?18:0))).toFixed(0));
  return{...plan,setupScore,convictionScore:conviction,learningAdjustment:learning.adjustment,learningSampleSize:learning.sampleSize,notes,eventRisks,eventRiskLocked,verdict:eventRiskLocked&&plan.verdict==="ENTER"?"NO_ENTRY":plan.verdict,context:{marketBias:marketContext.bias,marketRegime:marketContext.regime,breadth:marketContext.breadth,marketQuotes:marketContext.quotes,sectorEtf,sectorQuote,sectorAlignment,relativeStrengthMarketPct,relativeStrengthSectorPct,relativeStrengthGrade,regimeScore:marketContext.regimeScore,regimeReasons:marketContext.regimeReasons}}
}

async function runMarketScanInternal(forceFresh=true){
  const scanId=`scan_${Date.now().toString(36)}`,startedAt=new Date().toISOString();
  if(!provider.configured)return{scanId,startedAt,completedAt:new Date().toISOString(),mode:"DEMO" as const,provider:provider.name,market:{status:"UNKNOWN" as const},marketContext:{bias:"UNKNOWN" as const,regime:"UNKNOWN" as const,quotes:[]} as MarketContext,summary:"חסר FINNHUB_API_KEY. הסורק לא ימציא נתוני שוק.",candidates:demoOpportunities,discovery:[] as Array<{symbol:string;score:number;quote:MarketQuote}>,errors:[] as string[],stats:{universeSize:scanUniverse.length,dynamicSymbols:0,quoteSuccess:0,shortlisted:0,ohlcvValidated:0,dataQualityAvg:0,catalogSize:0,checkedToday:0,coveragePct:0,rotatingSymbols:0}};
  const providerDynamic=provider.getDynamicSymbols?await provider.getDynamicSymbols(forceFresh).catch(()=>[]):[];
  const rotatedDeepFinalists=takeFullMarketFinalists(fullMarketFinalistSlots).map(x=>x.symbol);
  const fullMarketLeaders=getFullMarketCandidates(18).map(x=>x.symbol);
  const dynamic=[...new Set([...providerDynamic,...rotatedDeepFinalists,...fullMarketLeaders])];
  const batch=await prepareDiscoveryBatch({catalogLoader:provider.getSupportedSymbols?()=>provider.getSupportedSymbols!(false):undefined,staticUniverse:scanUniverse,prioritySymbols:legacyPriority,dynamicSymbols:dynamic,quoteBudget,rotationBatchSize});
  const universe=batch.symbols;
  const [market,baseCtx]=await Promise.all([getCurrentMarketStatus(forceFresh),benchmarkContext(forceFresh)]),settled=await mapConcurrent(universe,discoveryConcurrency,s=>provider.getQuote(s,forceFresh)),errors:string[]=[];
  if(batch.catalogError)errors.push(`symbol catalog: ${batch.catalogError}`);
  const discovery=settled.flatMap((r,i)=>{if(r.status==="rejected"){errors.push(`${universe[i]} quote: ${r.reason instanceof Error?r.reason.message:String(r.reason)}`);return[]}const q=r.value;seedLiveQuote(q);if(!(q.price>=minPrice&&q.price<=maxPrice))return[];return[{symbol:q.symbol,score:discoveryScore(q),quote:q}]}).sort((a,b)=>b.score-a.score);
  const breadth=buildBreadth(discovery.map(x=>x.quote)),marketContext:MarketContext={...baseCtx,breadth},regimeAssessment=deriveRegimeAssessment(marketContext);marketContext.regime=regimeAssessment.regime;marketContext.regimeScore=regimeAssessment.score;marketContext.regimeReasons=regimeAssessment.reasons;
  const forcedFinalists=rotatedDeepFinalists.flatMap(symbol=>{const hit=discovery.find(x=>x.symbol===symbol);return hit?[hit]:[]});
  const forcedSet=new Set(forcedFinalists.map(x=>x.symbol));
  const exploration=batch.rotatingSymbols.length?discovery.filter(x=>batch.rotatingSymbols.includes(x.symbol)&&!forcedSet.has(x.symbol)).slice(0,Math.min(explorationSlots,Math.max(0,deepAnalysisMax-forcedFinalists.length-1))):[];
  const reserved=new Set([...forcedFinalists,...exploration].map(x=>x.symbol));
  const core=discovery.filter(x=>!reserved.has(x.symbol)).slice(0,Math.max(0,deepAnalysisMax-forcedFinalists.length-exploration.length));
  const shortlist=[...forcedFinalists,...core,...exploration].slice(0,deepAnalysisMax);
  const identities=await resolveSecurityMap(shortlist.map(x=>x.symbol));for(const [symbol,id] of identities)if(id.sectorEtf&&!sectorMap.has(symbol))sectorMap.set(symbol,id.sectorEtf);
  const sectorQuotes=await getSectorQuotes(shortlist.map(x=>x.symbol),forceFresh),tech=await mapConcurrent(shortlist,Math.min(2,shortlist.length),async item=>{const contextual=contextualize(await analyzeSymbol(item.symbol,market.status,item.quote,forceFresh),marketContext,sectorQuotes);return enrichFreeIntelligence(contextual,identities.get(item.symbol))}),candidates:TradePlan[]=[];tech.forEach((r,i)=>{if(r.status==="fulfilled")candidates.push(r.value);else errors.push(`${shortlist[i]?.symbol??"?"} technical: ${r.reason instanceof Error?r.reason.message:String(r.reason)}`)});
  const deepPool=mergeDeepCandidateCache(candidates,marketContext).map(plan=>{const eventRisks=eventRisksFor(plan.symbol),eventRiskLocked=eventRisks.some(e=>e.blocksEntry);return{...plan,eventRisks,eventRiskLocked,verdict:eventRiskLocked&&plan.verdict==="ENTER"?"NO_ENTRY":plan.verdict}});
  candidates.splice(0,candidates.length,...deepPool);
  candidates.sort((a,b)=>{const q=(b.dataQualityPct??0)-(a.dataQualityPct??0);return Math.abs(q)>=20?q:(b.convictionScore??b.setupScore*10)-(a.convictionScore??a.setupScore*10)});
  // Only technically usable candidates become recurring leaders. Rejected/level-less symbols no longer recycle into future scans.
  recordDiscoveryLeaders(candidates.filter(x=>(x.dataQualityPct??0)>=75&&x.playbook!=="NONE"&&x.entry&&x.stop&&x.tp1&&x.riskReward&&x.riskReward>=1.8&&x.quote).slice(0,12).map(x=>({symbol:x.symbol,score:x.convictionScore??x.setupScore*10,quote:x.quote!})));
  addLiveSymbols([...getActiveTrades().map(x=>x.symbol),...getWatchlist().map(x=>x.symbol),...candidates.map(x=>x.symbol)]);
  const triggered=candidates.filter(x=>x.verdict==="ENTER").length,armed=candidates.filter(x=>x.status==="ARMED").length,ohlcv=candidates.filter(x=>(x.dataQualityPct??0)>=70&&x.technicals).length,dq=candidates.length?Math.round(candidates.reduce((sum,x)=>sum+(x.dataQualityPct??0),0)/candidates.length):0,pre=market.status==="PRE"?" ב-Pre-Market לא מאשרים ביצוע עד שמחיר הסשן מאומת והמסחר הרגיל פתוח.":"",candle=provider.candlesConfigured?"":" אימות OHLCV מושבת עד להגדרת TWELVE_DATA_API_KEY.",fullStatus=getFullMarketSweepStatus();
  return{scanId,startedAt,completedAt:new Date().toISOString(),mode:"LIVE" as const,provider:provider.name,market,marketContext,summary:`סריקה ${scanId}: שכבת השוק המלא כיסתה ${fullStatus.checked}/${fullStatus.catalogSize||batch.catalogSize||0} (${fullStatus.coveragePct}%) בסבב ${fullStatus.sweepId}. בריצה הזו נבדקו ${universe.length} מחירים ו-${shortlist.length} פיינליסטיות חדשות עברו לניתוח עמוק; מאגר ה-Deep Analysis הטרי כולל ${candidates.length} מועמדות, מתוכן ${ohlcv} עם OHLCV מלא. ${triggered} טריגרים, ${armed} ממתינות. ${fullStatus.coveragePct<100?"הדירוג עדיין זמני עד להשלמת 100% מהסבב.":"קיים סבב שוק מלא שהושלם."}${candle}${pre}`,candidates,discovery:discovery.slice(0,40),errors,stats:{universeSize:universe.length,dynamicSymbols:dynamic.length,quoteSuccess:discovery.length,shortlisted:shortlist.length,ohlcvValidated:ohlcv,dataQualityAvg:dq,catalogSize:batch.catalogSize,checkedToday:batch.checkedToday,coveragePct:batch.coveragePct,rotatingSymbols:batch.rotatingSymbols.length,mustSymbols:batch.mustSymbols.length,explorationSlots:exploration.length,fullMarketFinalistSlots:forcedFinalists.length,fullMarketCoveragePct:fullStatus.coveragePct,fullMarketChecked:fullStatus.checked,fullMarketCatalogSize:fullStatus.catalogSize}}
}
let scanInFlight:Promise<Awaited<ReturnType<typeof runMarketScanInternal>>>|null=null,lastScanResult:Awaited<ReturnType<typeof runMarketScanInternal>>|null=null,lastScanCompletedAt=0;
export async function runMarketScan(forceFresh=true){
  if(scanInFlight)return scanInFlight;
  const age=Date.now()-lastScanCompletedAt;
  if(!forceFresh&&lastScanResult&&age<scanCacheMs)return{...lastScanResult,reused:true,cached:true};
  if(forceFresh&&lastScanResult&&age<scanCooldownMs)return{...lastScanResult,reused:true,cooldownRemainingSeconds:Math.max(1,Math.ceil((scanCooldownMs-age)/1000))};
  scanInFlight=runMarketScanInternal(forceFresh);
  try{const result=await scanInFlight;lastScanResult=result;lastScanCompletedAt=Date.now();return result}finally{scanInFlight=null}
}
let fullMarketWorker:NodeJS.Timeout|undefined;
function fullMarketStatus(){return{...getFullMarketSweepStatus(),workerActive:!!fullMarketWorker}}
export function getScannerStatus(){return{...getScannerCoverage(),quoteBudget,rotationBatchSize,deepAnalysisMax,explorationSlots,cooldownSeconds:Math.round(scanCooldownMs/1000),deepCache:getDeepCandidateCacheStatus(),fullMarket:fullMarketStatus()}}
export function getFullMarketStatus(){return fullMarketStatus()}
export function resetFullMarketDiscovery(){return resetFullMarketSweep()}
export async function advanceFullMarketDiscovery(){if(!provider.configured||!provider.getSupportedSymbols)return fullMarketStatus();const alpaca=alpacaFreeStatus();return advanceFullMarketSweep({catalogLoader:()=>provider.getSupportedSymbols!(false),quoteLoader:(s)=>provider.getQuote(s,true),batchQuoteLoader:alpaca.configured?async(symbols)=>{const snaps=await getAlpacaSnapshots(symbols),out:Record<string,MarketQuote>={};for(const [symbol,x] of Object.entries(snaps))if(x.quote)out[symbol]=x.quote;return out}:undefined,score:discoveryScore})}
export function startFullMarketDiscoveryWorker(){const enabled=(process.env.FULL_MARKET_SWEEP_ENABLED??"true").toLowerCase()!=="false",continuous=(process.env.FULL_MARKET_CONTINUOUS??"false").toLowerCase()==="true";if(!enabled||fullMarketWorker)return getFullMarketSweepStatus();const every=Math.max(10,Number(process.env.FULL_MARKET_SWEEP_TICK_SECONDS??15))*1000;const tick=async()=>{const state=await advanceFullMarketDiscovery();if(state.completedAt&&!continuous)stopFullMarketDiscoveryWorker()};fullMarketWorker=setInterval(()=>void tick(),every);setTimeout(()=>void tick(),500);return getFullMarketSweepStatus()}
export function stopFullMarketDiscoveryWorker(){if(fullMarketWorker){clearInterval(fullMarketWorker);fullMarketWorker=undefined}return getFullMarketSweepStatus()}
export async function getDashboard():Promise<DashboardSnapshot>{const engine={type:"DETERMINISTIC" as const,rulesetVersion:"3.0.2-deep-coverage",externalAi:false as const,estimatedCostUsd:0 as const},risk=portfolioRiskSummary(),activeTrades=getActiveTrades(),watchlist=getWatchlist(),ledgerCount=getClosedTrades().length;if(!provider.configured)return{mode:"DEMO",asOf:new Date().toISOString(),provider:{name:provider.name,configured:false,message:"יש להגדיר FINNHUB_API_KEY כדי להפעיל נתוני שוק חיים."},engine,market:{status:"UNKNOWN",bias:"UNKNOWN",regime:"UNKNOWN",benchmarks:[]},risk:{usedPct:risk.usedPct,maxPct:risk.maxPct,openRiskUsd:risk.openRiskUsd},opportunities:demoOpportunities,activeTrades,watchlist,ledgerCount};const scan=await runMarketScan(false);return{mode:"LIVE",asOf:new Date().toISOString(),provider:{name:provider.name,configured:true,message:!provider.candlesConfigured?"סריקת מחירים רחבה פעילה; יש להגדיר Twelve Data כדי לקבל OHLCV מלא.":scan.errors.length?scan.errors.slice(0,3).join(" | "):undefined},engine,market:{...scan.market,bias:scan.marketContext.bias,regime:scan.marketContext.regime,regimeScore:scan.marketContext.regimeScore,regimeReasons:scan.marketContext.regimeReasons,breadth:scan.marketContext.breadth,benchmarks:scan.marketContext.quotes},risk:{usedPct:risk.usedPct,maxPct:risk.maxPct,openRiskUsd:risk.openRiskUsd},opportunities:scan.candidates.filter(usableOpportunityCandidate).slice(0,10),activeTrades,watchlist,ledgerCount}}
export async function findTradeNow(){
  const scan=await runMarketScan(true); const validated:Array<{setup:TradePlan;gate:any;news:any;catalyst:any}>=[];
  let idx=0;
  for(const setup of scan.candidates.filter(usableOpportunityCandidate)){
    const news=await getNewsSignal(setup.symbol,true),catalyst=assessCatalyst(setup,news),gate=evaluatePreTradeGate(setup,scan.market.status,{headlineCritical:news.criticalNegative,catalystBlocked:catalyst.blocksEntry});
    let finalSetup:any={...setup,verdict:gate.verdict,portfolioGatePassed:gate.gates.portfolioCapacity&&gate.gates.sectorCapacity,portfolioGateReason:gate.blockers.find((x:string)=>x.includes("תיק")||x.includes("סקטור"))};
    try{
      const advanced=await buildAdvancedDecision(finalSetup,finalSetup.convictionScore??finalSetup.setupScore*10,idx<2);
      const advancedVerdict=advanced.judgeVerdict==="ENTER"?(scan.market.status==="OPEN"&&!finalSetup.dataFlags?.includes("DEEP_CACHE_REUSED")?"ENTER":"WAIT"):advanced.judgeVerdict==="ARMED"||advanced.judgeVerdict==="WAIT"?"WAIT":"NO_ENTRY";
      finalSetup={...finalSetup,advancedDecision:advanced,verdict:advancedVerdict};
    }catch{}
    validated.push({setup:finalSetup,gate,news,catalyst}); idx++;
  }
  const ready=validated.find(x=>x.setup.verdict==="ENTER"),armed=validated.find(x=>x.setup.verdict==="WAIT"&&x.setup.advancedDecision?.judgeVerdict==="ARMED")??validated.find(x=>x.setup.verdict==="WAIT"&&x.setup.status==="ARMED");
  const chosen=ready??armed;if(chosen)recordTradePlanDecision(chosen.setup,"ENTRY_CHECK");
  return{verdict:ready?"ENTRY_TRIGGERED" as const:armed?"ARMED" as const:"NO_EXECUTABLE_TRADE" as const,reason:ready?`${ready.setup.symbol} עברה גם את Pre-Trade Gate וגם את ועדת הראיות של v3.`:armed?`${armed.setup.symbol} היא המועמדת החזקה ביותר, אך ועדת הראיות עדיין מחכה לטריגר/אישור.`:`הסריקה ${scan.scanId} לא מצאה כרגע עסקה שעוברת גם את תנאי החובה וגם את ועדת הראיות.`,candidate:chosen?.setup,candidates:validated.map(x=>x.setup),scanId:scan.scanId,stats:scan.stats,errors:scan.errors}
}
export async function checkEntry(symbol:string){const normalized=symbol.trim().toUpperCase();if(!provider.configured){const reason="ספק נתוני השוק Finnhub אינו מוגדר, ולכן אי אפשר לבצע בדיקת כניסה חיה.";return{symbol:normalized,verdict:"NO_ENTRY" as const,reason,explanation:{verdictCode:"NO_ENTRY",verdictLabel:"לא נכנסים כרגע",title:`${normalized}: אין נתוני שוק`,primaryReason:reason,positives:[],blockers:[reason],nextSteps:["להגדיר FINNHUB_API_KEY ולהפעיל מחדש את הקונטיינר."],gateDetails:[],levels:{},snapshot:{}}};}
 try{await refreshEarningsCalendar(false)}catch{} const [market,base,identity]=await Promise.all([getCurrentMarketStatus(true),benchmarkContext(true),getSecurityIdentity(normalized,false).catch(()=>undefined)]);if(identity?.sectorEtf&&!sectorMap.has(normalized))sectorMap.set(normalized,identity.sectorEtf);const sectorQuotes=await getSectorQuotes([normalized],true);
 try{const raw=await analyzeSymbol(normalized,market.status,undefined,true),assessment=deriveRegimeAssessment(base),ctx:MarketContext={...base,regime:assessment.regime,regimeScore:assessment.score,regimeReasons:assessment.reasons},contextual=contextualize(raw,ctx,sectorQuotes),setup=await enrichFreeIntelligence(contextual,identity),news=await getNewsSignal(normalized,true),catalyst=assessCatalyst(setup,news),gate=evaluatePreTradeGate(setup,market.status,{headlineCritical:news.criticalNegative||Boolean(setup.secCriticalRisk),catalystBlocked:catalyst.blocksEntry||Boolean(setup.secCriticalRisk)});
    let finalSetup:any={...setup,verdict:gate.verdict,catalystScore:catalyst.score,catalystLabel:catalyst.label,portfolioGatePassed:gate.gates.portfolioCapacity&&gate.gates.sectorCapacity,portfolioGateReason:gate.blockers.find(x=>x.includes("תיק")||x.includes("סקטור"))};
    try{const advanced=await buildAdvancedDecision(finalSetup,finalSetup.convictionScore??finalSetup.setupScore*10,true);const finalVerdict=advanced.judgeVerdict==="ENTER"?(market.status==="OPEN"?"ENTER":"WAIT"):advanced.judgeVerdict==="ARMED"||advanced.judgeVerdict==="WAIT"?"WAIT":"NO_ENTRY";finalSetup={...finalSetup,advancedDecision:advanced,verdict:finalVerdict};if(finalVerdict!==gate.verdict)gate.warnings.push(`ועדת הראיות שינתה את פסק הדין מ-${gate.verdict} ל-${finalVerdict}.`)}catch{}
    recordTradePlanDecision(finalSetup,"ENTRY_CHECK");const localized=explainEntryHe(normalized,finalSetup.verdict,gate.blockers[0]??finalSetup.advancedDecision?.explanationHe??setup.thesis,gate.gates,finalSetup);return{symbol:normalized,verdict:finalSetup.verdict,reason:localized.primaryReason,explanation:localized,market,marketContext:ctx,news,catalyst,gates:gate.gates,portfolioGate:gate.portfolio,warnings:gate.warnings,setup:finalSetup,advancedDecision:finalSetup.advancedDecision}}catch(error){const technical=error instanceof Error?error.message:"שגיאת נתוני שוק",reason="לא ניתן להשלים כרגע את בדיקת הכניסה בגלל שגיאה בקבלת נתוני השוק.";return{symbol:normalized,verdict:"NO_ENTRY" as const,reason,technicalError:technical,explanation:{verdictCode:"NO_ENTRY",verdictLabel:"לא נכנסים כרגע",title:`${normalized}: בדיקת הנתונים נכשלה`,primaryReason:reason,positives:[],blockers:[reason],nextSteps:["להמתין מעט ולבצע בדיקה חדשה. אם התקלה חוזרת, לבדוק את מכסת ספקי הנתונים."],gateDetails:[],levels:{},snapshot:{}}}}}
export async function getQuote(symbol:string){if(!provider.configured)throw new Error("FINNHUB_API_KEY is not configured");return provider.getQuote(symbol,true)}
export async function getCandles(symbol:string,fresh=true){if(!provider.configured)throw new Error("FINNHUB_API_KEY is not configured");const now=Math.floor(Date.now()/1000);return provider.getCandles(symbol.trim().toUpperCase(),candleResolution,now-lookbackDays*86400,now,fresh)}
export function getRuntimeConfig(){return{mode:provider.configured?"LIVE" as const:"DEMO" as const,provider:provider.name,providerConfigured:provider.configured,quoteProvider:provider.quoteProviderName,candleProvider:provider.candleProviderName,candlesConfigured:provider.candlesConfigured,engine:"DETERMINISTIC" as const,externalAi:false,modelCostUsd:0,rulesetVersion:"3.0.2-deep-coverage",scanUniverse,legacyPriority,marketSymbols,sectorMap:Object.fromEntries(sectorMap.entries()),candleResolution,lookbackDays,shortlistSize,deepAnalysisMax,minPrice,maxPrice,automationEnabled:(process.env.AUTOMATION_ENABLED??"true").toLowerCase()!=="false",scanIntervalMinutes:Number(process.env.SCAN_INTERVAL_MINUTES??10),triggerPollSeconds:Number(process.env.TRIGGER_POLL_SECONDS??60),shadowTradingEnabled:(process.env.SHADOW_TRADING_ENABLED??"true").toLowerCase()!=="false",brokerMode:"STAGED_ONLY",livePricesEnabled:(process.env.LIVE_PRICES_ENABLED??"true").toLowerCase()!=="false",scanQuoteBudget:quoteBudget,rotationBatchSize,fullMarketFinalistSlots,fullMarketAutostart:(process.env.FULL_MARKET_AUTOSTART??"false").toLowerCase()==="true",alpacaFree:alpacaFreeStatus(),secIntelligenceEnabled:true,minDataConfidenceScore:Number(process.env.MIN_DATA_CONFIDENCE_SCORE??70),maxExecutionSpreadPct:Number(process.env.MAX_EXECUTION_SPREAD_PCT??0.8),accountValueUsd:Number(process.env.ACCOUNT_VALUE_USD??0),defaultTradeRiskPct:Number(process.env.DEFAULT_TRADE_RISK_PCT??0.5),maxPortfolioRiskPct:Number(process.env.MAX_PORTFOLIO_RISK_PCT??3),minOpportunityScore:Number(process.env.MIN_OPPORTUNITY_SCORE??6.5),minOpportunityDataQuality:Number(process.env.MIN_OPPORTUNITY_DATA_QUALITY??75),minOpportunityRR:Number(process.env.MIN_OPPORTUNITY_RR??2),storage:storageStatus()}}
export function getScanUniverse(){return[...scanUniverse]}
export function getSectorForSymbol(symbol:string){return sectorMap.get(symbol.toUpperCase())}
export function calculatePositionSize(params:{accountValueIls:number;riskPct:number;entry:number;stop:number;usdIls:number}){const{accountValueIls,riskPct,entry,stop,usdIls}=params,riskBudgetIls=accountValueIls*(riskPct/100),riskPerShareUsd=Math.abs(entry-stop);if(riskPerShareUsd<=0||usdIls<=0)throw new Error("entry/stop/usdIls must create positive risk");const riskPerShareIls=riskPerShareUsd*usdIls,quantity=Math.floor(riskBudgetIls/riskPerShareIls);return{quantity,riskBudgetIls:Number(riskBudgetIls.toFixed(2)),estimatedRiskIls:Number((quantity*riskPerShareIls).toFixed(2)),positionValueUsd:Number((quantity*entry).toFixed(2))}}
