import { getActiveTrades, updateTradeMarket } from "./portfolio.js";
import { getCandles, getQuote } from "./trader.js";
import { atr } from "./analytics.js";
import { getLivePrice } from "./live-prices.js";

export type ManagementAction="VERIFY_STOP"|"TP2_REACHED"|"TP1_REACHED"|"CONSIDER_BREAKEVEN"|"PROTECT_PROFIT"|"HOLD_PLAN"|"THESIS_REVIEW"|"WAIT_FOR_FILL";
const actionHe:Record<ManagementAction,string>={VERIFY_STOP:"הסטופ הגיע — בדוק ביצוע בברוקר",TP2_REACHED:"יעד 2 הושג",TP1_REACHED:"יעד 1 הושג",CONSIDER_BREAKEVEN:"אפשר לשקול מעבר לנקודת איזון",PROTECT_PROFIT:"כדאי לבחון הגנה על הרווח",HOLD_PLAN:"להמשיך לפי התוכנית",THESIS_REVIEW:"נדרשת בדיקת תזה",WAIT_FOR_FILL:"התוכנית עדיין לא בוצעה בפועל"};
function pct(a:number,b:number){return b?Number(((a/b-1)*100).toFixed(2)):undefined}
export async function getTradeManagementPlan(id:string){
  const trade=getActiveTrades().find(x=>x.id===id);if(!trade)throw new Error("trade_not_found");
  let price=getLivePrice(trade.symbol)?.price??trade.current;try{if(!price){const q=await getQuote(trade.symbol);price=q.price;updateTradeMarket(trade.id,q.price)}}catch{}
  if(trade.executionState==="PLANNED")return{tradeId:id,symbol:trade.symbol,action:"WAIT_FOR_FILL" as ManagementAction,actionLabel:actionHe.WAIT_FOR_FILL,reason:"זו עדיין תוכנית בלבד. אין לנהל P&L או להזיז סטופ כאילו בוצעה קנייה בפועל.",mutatesTrade:false,executionState:trade.executionState,entry:trade.entry,stop:trade.stop,tp1:trade.tp1,tp2:trade.tp2,quantity:trade.quantity,autoLevelManagement:trade.autoLevelManagement,tp1HitAt:trade.tp1HitAt,tp2HitAt:trade.tp2HitAt,stopHitAt:trade.stopHitAt};
  if(!(trade.entry&&price))return{tradeId:id,symbol:trade.symbol,action:"THESIS_REVIEW" as ManagementAction,actionLabel:actionHe.THESIS_REVIEW,reason:"אין כרגע מחיר שוק אמין. לא משנים את התוכנית על בסיס מידע חלקי.",mutatesTrade:false};
  const direction=trade.side==="LONG"?1:-1,originalRisk=trade.originalStop?Math.abs(trade.entry-trade.originalStop):trade.stop?Math.abs(trade.entry-trade.stop):0,currentR=originalRisk>0?Number((((price-trade.entry)*direction)/originalRisk).toFixed(2)):undefined;
  const unrealizedPnlUsd=Number(((price-trade.entry)*trade.quantity*direction).toFixed(2)),unrealizedPct=pct(price,trade.entry),stopDistancePct=trade.stop?Math.abs(Number(((price/trade.stop-1)*100).toFixed(2))):undefined,tp1DistancePct=trade.tp1?Number(((trade.tp1/price-1)*100).toFixed(2)):undefined,tp2DistancePct=trade.tp2?Number(((trade.tp2/price-1)*100).toFixed(2)):undefined;
  let action:ManagementAction="HOLD_PLAN",reason="לא הגיע כרגע תנאי דטרמיניסטי שמצדיק שינוי. ממשיכים לפי התוכנית המקורית.",suggestedStop:number|undefined;
  const stopHit=trade.stop!=null&&(trade.side==="LONG"?price<=trade.stop:price>=trade.stop),tp2Hit=trade.tp2!=null&&(trade.side==="LONG"?price>=trade.tp2:price<=trade.tp2),tp1Hit=trade.tp1!=null&&(trade.side==="LONG"?price>=trade.tp1:price<=trade.tp1);
  if(stopHit){action="VERIFY_STOP";reason="המחיר הגיע לרמת הסטופ או עבר אותה. יש לבדוק את ה-Fill האמיתי בברוקר; Trader OS לא ממציאה יציאה."}
  else if(tp2Hit){action="TP2_REACHED";reason="יעד 2 הושג. בדוק ביצוע בפועל וסגור/נהל את היתרה לפי התוכנית."}
  else if(tp1Hit){action="TP1_REACHED";reason="יעד 1 הושג. אפשר לרשום מימוש חלקי ולבחון הגנת רווח, בהתאם לתוכנית המקורית."}
  else if(trade.thesisStatus==="INVALIDATED"){action="THESIS_REVIEW";reason="התזה המקורית מסומנת כלא תקפה. עדיפות לבדיקת יציאה וסיכון, לא להמתנה מתוך תקווה."}
  else if((currentR??0)>=1.5){action="PROTECT_PROFIT";suggestedStop=trade.side==="LONG"?Math.max(trade.stop??trade.entry,trade.entry):Math.min(trade.stop??trade.entry,trade.entry);reason="העסקה מעל +1.5R. ניתן לבחון הגנת רווח בנקודת האיזון או במבנה מחיר חדש, בלי להרחיב סיכון."}
  else if((currentR??0)>=1){action="CONSIDER_BREAKEVEN";suggestedStop=trade.entry;reason="העסקה סביב +1R. מעבר לנקודת איזון הוא אפשרות, לא פעולה אוטומטית; יש לוודא שהמבנה עדיין מאפשר תנודתיות רגילה."}
  if(trade.trailingMode==="ATR"||trade.trailingMode==="STRUCTURE"){try{const candles=await getCandles(trade.symbol,false),complete=candles.slice(-120);let candidate:number|undefined;if(trade.trailingMode==="ATR"){const a=atr(complete,14);if(a&&price)candidate=trade.side==="LONG"?price-a*2:price+a*2}else{const lows=complete.slice(-18).map(c=>c.low),highs=complete.slice(-18).map(c=>c.high);if(trade.side==="LONG"&&lows.length)candidate=Math.min(...lows);if(trade.side==="SHORT"&&highs.length)candidate=Math.max(...highs)}if(candidate&&trade.stop){const improves=trade.side==="LONG"?candidate>trade.stop&&candidate<price:candidate<trade.stop&&candidate>price;if(improves){suggestedStop=Number(candidate.toFixed(2));action="PROTECT_PROFIT";reason=trade.trailingMode==="ATR"?`מדיניות Trailing לפי ATR מציעה להדק את הסטופ לכ-$${suggestedStop}. זו הצעה בלבד — אין שינוי אוטומטי.`:`מדיניות Trailing לפי מבנה מזהה רמת הגנה חדשה סביב $${suggestedStop}. זו הצעה בלבד — אין שינוי אוטומטי.`}}}catch{}}
  return{tradeId:id,symbol:trade.symbol,executionState:trade.executionState,price,entry:trade.entry,stop:trade.stop,originalStop:trade.originalStop,tp1:trade.tp1,tp2:trade.tp2,quantity:trade.quantity,initialQuantity:trade.initialQuantity??trade.quantity,partialExits:trade.partialExits??[],partialRealizedPnlUsd:trade.partialRealizedPnlUsd??0,unrealizedPnlUsd,unrealizedPct,currentR,stopDistancePct,tp1DistancePct,tp2DistancePct,riskUsd:trade.riskUsd,riskPct:trade.riskPct,thesisStatus:trade.thesisStatus,trailingMode:trade.trailingMode,autoLevelManagement:trade.autoLevelManagement,tp1HitAt:trade.tp1HitAt,tp2HitAt:trade.tp2HitAt,stopHitAt:trade.stopHitAt,mfePct:trade.mfePct,maePct:trade.maePct,action,actionLabel:actionHe[action],reason,suggestedStop,mutatesTrade:false,brokerExecution:false,lastUpdatedAt:trade.lastUpdatedAt,timeline:(trade.timeline??[]).slice(-20).reverse()};
}
